- README.md
- mixer/api/v1/attributes.proto
- mixer/api/v1/check.proto
- mixer/api/v1/quota.proto
- mixer/api/v1/report.proto
- mixer/api/v1/service.proto
- mixer/config/v1/attribute_descriptor.proto
- mixer/config/v1/log_entry_descriptor.proto
- mixer/config/v1/metric_descriptor.proto
- mixer/config/v1/monitored_resource_descriptor.proto
- mixer/config/v1/principal_descriptor.proto
- mixer/config/v1/quota_descriptor.proto
This clearly separates mixer's API and configuration surface from
the implementation. This is designed to make it possible to
replace the mixer in a fully compatible way.
Note that I put the config into mixer/config instead of istio/config since it is in fact all specific to the mixer. These configuration definitions aren't used by the proxy or manager themselves.
Note to Doug: this clearly doesn't build as it needs the bazel treatment (mainly a WORKSPACE file I think). I hope you can supply this after this initial checkin.
> Migrate mixer API and config to this repo.

- mixer/v1/config/aspect/logger_config.proto
- mixer/v1/config/descriptor/log_entry_descriptor.proto
LoggerConfig, for the moment, will consist of name for the logs collection and a list of descriptor names for log entries.
The log_entry_descriptor is also updated to include metadata about a special payload attribute. Non-payload attributes will be considered metadata attributes about the detail provided in the payload.
> Add logger aspect config

- mixer/v1/config/descriptor/quota_descriptor.proto
PER_SECOND_LIMIT and PER_MINUTE_LIMIT cannot both have an index of 1.
> Fix enum in quota descriptor

- mixer/v1/config/descriptor/log_entry_descriptor.proto
At the moment, there is no way to distinguish the formats of various payloads sent via the payload attribute to mixer to enable better processing of the payloads.
This PR establishes support for structured payloads (serialized JSON). This will enable structured loggers to better include the payload in their generated logs.
> Add payload format to LogEntryDescriptor.

- mixer/v1/config/descriptor/quota_descriptor.proto
- mixer/v1/quota.proto
This generalizes refresh windows and eliminates the API level distinction between allocation and rate quotas.
Allocated quota now just has an expiration period which determines when how long an allocation 'survives' until it is automatically freed. If you specify a expiration time of 0, then the quota is never freed.
This removes the notion of precise/imprecise quotas. That was just a leftover of how things are handled in GCP and isn't really an appropriate top-level concern.
> Streamline QuotaDescriptor.

- mixer/v1/config/descriptor/value_type.proto
Adds STRING_MAP value type.
Typically used by headers.
> add STRING_MAP value type

- mixer/v1/check.proto
- mixer/v1/quota.proto
Quota had a TTL value expressed in terms of absolute time.
This unfortunately is useless in a distributed system.
Now both QuotaResponse and CheckResponse carry a Duration value
represent how long the response is valid for.
> Provide TTL values for Check and Quota responses.

- proxy/v1/config/cfg.md
- proxy/v1/config/cfg.proto
Just moving fault injection into route rule as discussed during the calls. Retained all docs, etc.
> Move fault injection into route rule

- mixer/v1/config/cfg.proto
- mixer/v1/config/descriptor/monitored_resource_descriptor.proto
- mixer/v1/config/descriptor/principal_descriptor.proto
As a stopgap so we can make progress independent of @mandarjog's https://github.com/istio/api/pull/45, we add `repeated` descriptor fields to the global config. We also change the `MonitoredResourceDescriptor` and `PrincipalDescriptor` protos to use `LabelDescriptors` rather than `repeated string attributes`. This should let us close https://github.com/istio/api/issues/49.
> Add descriptors to the mixer's global config

- proxy/v1/config/cfg.proto
We would like to eliminate the use of flags from the manager images, since they are prone to errors and lead to inconsistency. The plan is to import the config values to components from a `ConfigMap`.
> Define proxy mesh global variables

- proxy/v1/config/cfg.md
- proxy/v1/config/cfg.proto
This PR adds support for specifying timeout per retry in our route rule specification (corresponding support has been added in Envoy lyft/envoy#756). Together, we now have global timeout budget, per retry timeout with jitter between retries, max retries, and policies that govern when a retry should be attempted.
> proxy config: per retry timeout

- mixer/v1/config/descriptor/metric_descriptor.proto
This is needed to provide instruction to backends and adapters to treat
values as observations within a histogram. This will enable
adapters/backends to more readily monitor values that are distributions
when they have native support for distribution values.
Example uses:
- prometheus (histograms:
https://prometheus.io/docs/concepts/metric_types/#histogram)
- statds (timings:
https://github.com/etsy/statsd/blob/master/docs/metric_types.md#timing)
- stackdriver (distributions:
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TypedValue#Distribution)
The documentation for the bucket definitions (and actual proto messages)
are taken from existing stackdriver custom metrics protos for
distributions.
NOTE: individual reports can still be single-valued. Adapters that
support distributions …
> Add distribution kind to metric_descriptor.

- proxy/v1/config/cfg.proto
Needed for ingress to expose its external IP. See: https://github.com/istio/manager/pull/562
> Add ingress service to the proxy mesh

- mixer/v1/config/descriptor/metric_descriptor.proto
- mixer/v1/config/descriptor/monitored_resource_descriptor.proto
Apparently you need a space or it breaks. Clean up some whitespace I noticed while checking the other files.
> Update metric descriptor code comments so they'll be rendered correctly

- proxy/v1/config/proxy_mesh.proto
This PR adds a field to configure the proxy for statsd export via UDP. For envoy configuration, it will be used to populate the new "statsd_udp_ip_address" field.
> Add support for sending statsd export config

- proxy/v1/config/route_rule.proto
This is necessary to make a route rule a self-contained object.
> Add name field to a rule

- proxy/v1/config/ingress_rule.proto
This definition captures the effective use of the route rules in the ingress controller in Pilot. The route rules fields that are missing are simply ignored by the implementation. Hoping to get this merged so we can transition to one-proto-per-type in the config system.
> Introduce ingress rule

- mixer/v1/config/cfg.proto
Add proto definition for the new service config.
Defines the Constructor, Action, Handler and Rule concept for the new mixer configuration model.
> New service config model

- mixer/v1/check.proto
Turns out we need to also match on "doesn't exist" for caching to work
properly. So add an "ABSENCE" match condition. Also, fold PREFIX into REGEX.
> More API tweaks.

- mixer/v1/global_dictionary.yaml
To support TCP policy and telemetry, we are adding the following attributes to the global list:
- `connection.id` (unique ID for a connection)
- `connection.received.bytes` (bytes received since last Report())
- `connection.received.bytes_total` (total bytes received during lifetime of connection)
- `connection.sent.bytes` (bytes sent since last Report())
- `connection.sent.bytes_total` (total bytes sent during lifetime of connection)
- `connection.duration` (total duration of the connection)
- `context.protocol` (used to distinguish mode of Check()/Report(), for example: `tcp`, `http`)
- `context.timestamp` (timestamp of Check() or Report())
> Update global_dictionary.yaml with TCP attributes

- mixer/v1/global_dictionary.yaml
To be consistent with request.time and response.time.  It should be context.time not context.timestamp.
> add context.time

- mixer/v1/global_dictionary.yaml
Integer strings, such as 200, 0, and 1, were added with single quote, such as '200', '1' and '0'.  These have to be added without single quote.
Also add some popular http response codes
> Add common integer strings.

- proxy/v1/config/route_rule.proto
fixing duplicate field numbering in route_rule.proto
cc @esbie LMK if this works. If changing the numbering is not going to work for you, I can keep them as is and bump the websocket_upgrade field's number alone. I am assuming that you are not running this live at the moment.
> renumbering fields

- proxy/v1/config/proxy_mesh.proto
Allow user to disable checks (but keep reports on) for mixer.
> Option to disable mixer checks

- proxy/v1/config/egress_rule.proto
Convert from multiple domains per egress rule to a single domain per egress rule. Reuse the destination structure defined in route_rule and cleanup the description.
> Use one domain per egress rule

- proxy/v1/config/proxy_mesh.proto
This flag specifies the availability zone associated with an envoy instance. Part of the solution for https://github.com/istio/pilot/issues/1212
> add service-zone flag to proxy config

- proxy/v1/config/route_rule.proto
From `string destination` to `IstioService destination`
> Use proper destination field type in DestinationWeight

- proxy/v1/config/dest_policy.proto
- proxy/v1/config/route_rule.proto
Changing docs URL due to recent migration from lyft.github.io to envoyproxy.github.io
> lyft->envoyproxy

- mixer/v1/template/extensions.proto
In order to support templates to be defined outside Mixer repo, we need to move out the TemplateExtension.proto from https://github.com/istio/mixer/blob/master/pkg/adapter/template/TemplateExtensions.proto into istio.io/api/mixer/v1/template. If the TemplateExtensions.proto is in Mixer repo, it was causing cyclic includes when trying to compile a Template outside Mixer repo that depends on Mixer.
There will be one following PR in the Mixer repo that changes all of the the existing defined templates to use the one from this new location. It will also delete the old TemplateExtensions.proto inside the Mixer repo.
> Add Template Extension proto inside istio.io/api/mixer/v1/template

- mixer/v1/global_dictionary.yaml
Without this change, we get flooded with
```
0923 02:31:03.459056       1 protoBag.go:68] Attribute 'source.service' not in either global or message dictionaries
``` 
in Mixer logs.
> Add source.service to global dictionary

- proxy/v1/config/attributes.proto
This one is for Proxy config.  Pilot will use it to set mesh attributes to Istio Proxy.
> Add attribute proto.

- BUILD
- WORKSPACE
- api.bzl
- gogoproto/BUILD
- google/rpc/BUILD
- mixer/v1/BUILD
- mixer/v1/config/BUILD
- mixer/v1/config/descriptor/BUILD
- mixer/v1/template/BUILD
- prow/api-presubmit.sh
Unfortunately, the fix to expose WKT for C++ was merged on Sep 5 and has missed protobuf 3.4.1.
Pointing to master as a temporary workaround.
I checked that both mixerclient and mixer build fine against this PR.
> C++ bazel rules for API

- mixer/v1/attributes.proto
- mixer/v1/check.proto
- mixer/v1/report.proto
So that UncompressedAttributes can be called Attributes. 
Now it is good time to name it properly.  It will be much harder to do it once they are used all over the places.
> Rename Attributes to CompressedAttributes.

- mixer/v1/attributes.proto
To support attribute update.  Update may replace or erase an attribute. 
Mixerclient plans to use this message to replace its Attributes class.
> Change proto Attributes to use map.

- mixer/v1/config/client/api_spec.proto
- mixer/v1/config/client/mixer_filter_config.proto
* Rename APISpec to HTTPAPISpec throughout
* Add EXPERIMENTAL regex pattern to HTTPAPISpecPattern to enable performance analysis and comparison between `uri_template` and `regex` pattern matching.
> Rename APISpec to HTTPAPISpec

- proxy/v1/config/proxy_mesh.proto
- proxy/v1/config/route_rule.proto
The max obj len field is required to create readable statistics.
CORS is standard http cors policy.
Mirroring is traffic mirroring (requested by some users).
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>
> mirroring, max obj len, cors

- mixer/v1/config/client/mixer_filter_config.proto
A single mixerclient may serve multiple destination services. Aspects
of runtime configuration must therefore be defined per-service,
e.g. Quota, APISpec. Express this per-service configuration as a map
of config elements indexed by the fully qualified destination service,
e.g. destination.service.
As an implementation note, the mixerclient could derive
destination.service using the `host` header. Alternatively, Pilot can
populate inbound route's opaque_config with the canonical destination
service name. The mixerclient can use the destination service
name as key into the runtime configuration to determine the
approptiate quota, apispec, etc. This has the nice property of
automatically handling all domain name variations, e.g. my-service,
my-service.my-namespace, …
> Define per-service mixerclient runtime configuration

- mixer/v1/config/client/api_spec.proto
- mixer/v1/config/client/mixer_filter_config.proto
- mixer/v1/config/client/quota.proto
- mixer/v1/config/client/service.proto
NOTE: posted for early review. I'll rebase+merge after repo consolidation is finished.
gogoproto options seem to be infectious on dependent protobufs. Make
the following changes to enable mixerclient protobufs to be built with
gogoslick_proto_library.
1) Mirror attributes.go options into mixerclient protobufs to avoid
errors about undefined methods, e.g.
`this.Attributes.Equal undefined (type *istio_mixer_v1.Attributes has no field or method Equal)`
2) duplicate proxy.v1.config.IstioService and
proxy.v1.config.StringMatch into mixer.v1.config.client to avoid
polluting proxy protobufs with gogoproto options. Resulting jsonpb
encoding is the same for c++ mixerclient.
> fix mixerclient build with gogoslick_proto_library

- proxy/v1/config/proxy_mesh.proto
This change is in order to reuse AuthenticationPolicy enum for per-service enablement.
Issue: https://github.com/istio/auth/issues/267
Design doc:
https://docs.google.com/document/d/1D7wZCQjVB72Wlwr5ZxP5WUmn3FUDr-XzfX8OodPXe8Y/edit#heading=h.eg4nr9f3mo7h
> Add INHERIT to AuthenticationPolicy enum.

- mixer/v1/config/client/mixer_filter_config.proto
Protobuf field names should be hyphen with lower case instead of camel case.  to be consistent with other field names.
> rename field to disable_tcp_check_calls.

- mixer/v1/config/client/client_config.proto
Currently TCP is using the same HTTP client config.  It is a hack. This PR will try to separate them.
The changes are:
* Renamed mixer_filter_config to client_config  in the file name and message name
* Rename MixerControlConfig as ServiceConfig.  It is under mixer::v1::config::client name space so it will not cause confusing.
* Add a new message TransportConfig for cache and network policy
* Create separate HttpClientConfig and TcpClientConfig.
* Add disable_report_calls for tcp too.
> Separate http client config with tcp.

- proxy/v1/config/egress_rule.proto
- proxy/v1/config/route_rule.proto
This reverts commit 84f7ea18d778de7c448582071f59f192451e1d8d.
This is causing istio/istio to break when updating to latest version of istio/api
errors: 
```
ERROR: /Users/guptasu/go/src/istio.io/istio/pilot/model/BUILD:3:1: GoCompile pilot/model/~normal~go_default_library~/istio.io/istio/pilot/model.a failed (Exit 1).
pilot/model/validation.go:868:29: port.Port undefined (type *istio_proxy_v1_config.Port has no field or method Port)
pilot/model/validation.go:869:72: port.Port undefined (type *istio_proxy_v1_config.Port has no field or method Port)
pilot/model/validation.go:871:13: port.Port undefined (type *istio_proxy_v1_config.Port has no field or method Port)
pilot/model/validation.go:941:35: undefined: istio_proxy_v1_config.EgressRule_Port
2017/11/20 11:11:31 error running compiler: …
```
> Revert "port spec (#235)"

- .gitignore
- Makefile
- bin/getVersion.sh
This PR removes the install into GOPATH of the go tools need for proto-compile. Instead, the tools are installed into a new `bin` directory (which also houses a script to extract tooling version from the lock file).
> Update Makefile to use local builds of deps for protoc

- routing/v1alpha1/dest_policy.pb.go
- routing/v1alpha1/dest_policy.proto
minimum time the circuit will be **open** instead of **closed** as it was previously.
The circuit is _open_ = "no traffic".
> fix the comment of sleep window of circuit breaker

- mixer/v1/template/extensions.pb.go
- mixer/v1/template/standard_types.pb.go
- mixer/v1/template/standard_types.proto
After this PR, I will replace all the existing templates to use standard_type:Value instead of ValueType enum. In the same PR I will also introduce pkg/adapter/ValueType enum which will be referenced by all the adapters instead of api/mixer/v1/config/descriptor/ValueType.
> Introduce Value for template-time equivalent of ValueType enum.

- STYLE-GUIDE.md
The acronym part is controversial. Envoy and Google APIs don't use acronyms, but Istio so far uses acronyms. Unfortunately, Go chose to use acronyms, so we have to choose one way or the other. :P
> Introducing basic naming convention.

- mixer/v1/config/client/client_config.pb.go
- mixer/v1/config/client/client_config.proto
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Add config description that the TCP filter report interval should be at least one second.
> Update comment for TCP filter report interval config.

- Gopkg.lock
- Makefile
- broker/dev/istio.broker.dev.pb.html
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
- mixer/v1/config/descriptor/istio.mixer.v1.config.descriptor.pb.html
- mixer/v1/config/istio.mixer.v1.config.pb.html
- mixer/v1/istio.mixer.v1.pb.html
- mixer/v1/template/istio.mixer.v1.template.pb.html
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- routing/v1alpha1/istio.routing.v1alpha1.pb.html
- routing/v1alpha2/istio.routing.v1alpha2.pb.html
- Was passing a incorrect directory when building the protoc-gen-doc plugin. Not sure how come this worked before,
but the directory was definitely incrrect.
- Sync to the latest doc gen tool.
> Correct a small makefile issue

- Makefile
- mixer/v1/check.pb.go
Without it, we get a panic about dual registration of googleapis protos:
https://storage.googleapis.com/istio-prow/pull/istio_istio/4300/istio-unit-tests/2402/build-log.txt
> Switch to the actual gogo googleapis

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/external_service.pb.go
- networking/v1alpha3/external_service.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
Without these fixes, istioctl won't accept those examples
- Quoted names with wildcard
- Removed redundant dash before keys of a map
> Syntax fix to the examples in the docs of networking

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
based on the documentation of Envoy sni_domains - https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto.html?highlight=sni_domains 
> May contain a wildcard prefix for the bottom-level domain of a domain name, e.g. *.example.com. Note that foo.example.com will be matched by foo.example.com and *.example.com SNI domain names, but not by *foo.example.com, *oo.example.com, *example.com, *.com or *.
> clarify wildcard usage in gateway server hosts

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
Docstrings only.  Explains how to use ServiceEntry for unix domain socket endpoints.
Signed-off-by: Spike Curtis <spike@tigera.io>
> Unix domain sockets on ServiceEntry

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Especially hide portselector.name, which is not implemented.
> hide unused fields in networking protos from docs

- mixer/v1/global_dictionary.yaml
`context.reporter.proxy` has values `client` or `server` for the two sidecars on the data path.
`context.reporter.uid` carries the UID value of the pod.
> attributes: add context reporter attributes

- mixer/v1/global_dictionary.yaml
Add attributes to hold gRPC return status. 
gRPC uses h2 trailers which are missing right now in the attribute vocabulary (we only have h2 headers).
xref: https://github.com/istio/proxy/issues/1805
> attributes: grpc message and status

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
Correct destination field from "name" to "host" in VirtualService for Gateway example.
> Fix VirtualService in Gateway example for v1alpha3

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
In [HTTPMatchRequest ] (https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPMatchRequest) , a http match can be described by  _uri(StringMatch), schema(StringMatch), headers map<string, StringMatch>(StringMatch)_ ... . **uri** is a brother filed of http.match.**headers** , not a key of headers map. It is a little confusing to use uri as a key of headers map, even though syntax is ok.
> uri should be under http.match rather than under http.match.headers according to the spec of HTTPMatchRequest.

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
As seen [in envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#enum-route-virtualhost-tlsrequirementtype) and [istio usage](https://github.com/istio/istio/blob/f3c0f5f9f86b80dc67af5e91622532516ecddc71/pilot/pkg/networking/core/v1alpha3/gateway.go#L348).
> Fix incorrect doc statement about HTTPS redirect.

- mixer/v1/global_dictionary.yaml
Values are "inbound" and "outbound". This is a replacement for context.reporter.local.
/assign @douglas-reid @geeknoid 
> attributes: define context.reporter.type

- mixer/v1/global_dictionary.yaml
Due to collision with a go keyword.
> attributes: rename attribute type to kind

- mixer/v1/global_dictionary.yaml
Will use Envoy's Network::Connection::requestedServerName() method
> add connection.requested_server_name attribute (SNI)

- mixer/v1/global_dictionary.yaml
The two attributes will be populated by https://github.com/istio/proxy/pull/1837
cc @douglas-reid @kyessenov @qiwzhang
> Add two new attributes: request.url_path and request.query_params

- mixer/v1/global_dictionary.yaml
Reverts istio/api#608
re-ordering of dictionary elements in not allowed.
Please append to the end.
@geeknoid
> Revert "add rbac attributes to mixer global dict (#608)"

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Envoy doesn't need that the total weight of all routes be equal to 100. This PR updates the documentation related to the same. Refer to [this comment](https://github.com/istio/istio/pull/9112#discussion_r222797735) in istio/istio#9112 for more information.
> Update documentation related to weighted routes

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
`s/gatweway/gateway`
Modified `gateway.proto` then generated the 2 other files.
> Fix typo in gateway.proto

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
This is a minor correction to prevent user confusion in the istio.io reference doc for ServiceEntry.
> Minor correction to avoid confusion in ServiceEntry reference doc

- .circleci/config.yml
- Makefile
- prototool.yaml
- prow/api-presubmit.sh
- scripts/pre-commit
- tools/all/Dockerfile
Note: I want to add FIXMES and Github issues for the files in the `ignores:` section of prototool.yaml. If this looks good I'll add those before submitting
> Add prototool for linting, precommit, Circle, Prow.

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
in the latest envoyproxy.io (1.9) api-v1 was removed
> remove references to envoyproxy.io api-v1

- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
- policy/v1beta1/istio.policy.v1beta1.pb.html
Clarify that header names are literals but values are expressions.
/assign @geeknoid 
/assign @ozevren 
> policy: documentation for route directive

- WORKSPACE
- scripts/check-repositories
- scripts/pre-commit
To use --distdir option of Bazel (which allows to use previously
fetched tarballs instead of downloading dependencies during
build), all dependencies should use http instead of git and need
to have sha256 sums specified.
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
> bazel: Allow to distdir all dependencies

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
(in place of https://github.com/istio/istio.io/pull/2893)
> clarify http match example

- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
- policy/v1beta1/istio.policy.v1beta1.pb.html
- proto.lock
- python/istio_api/policy/v1beta1/cfg_pb2.py
https://github.com/istio/istio/issues/7637
@mandarjog This is a draft and I hope to get your early review. I am going to make a prototype with this config to make sure it works as expected. I've considered to reuse the [TLSSettings](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSSettings), but it does not quite match  oop adapter auth.
> oop adapter connection auth config

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/network.proto
Fix some spelling errors:
1. "overriden" to "overridden".
2. "assinged" to "assigned".
> Fix some spelling errors

- proto.lock
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
Signed-off-by: Yangmin Zhu <ymzhu@google.com>
> Update RBAC for Authorization v2 API.

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
Update comment for credentialName.
When customer specifies credentialName (e.g. "foo.credential"), and use MUTUAL TLS.
Gateway workloads will send SDS requests with resource name "foo.credential" to retrieve serverCertificate and privateKey, and send SDS requests with resource name "foo.credential-cacert" to retrieve CaCertificates. In Kubernetes, customer needs to create a Kubernetes secret named "foo.credential", which contains server certificate, the private key, and the CA certificate.
If customer specifies credentialName (e.g. "foo.credential"), and use SIMPLE TLS. Gateway workload will only send SDS requests with resource name "foo.credential" to retrieve serverCertificate and privateKey. And the Kubernetes secret named "foo.credential" only contains server certificate and private …
> Update comment for credentialName

- Makefile
When preparing modifications to this repo, the pre-commit hook uses docker to run some containers and tools to generate code.
The files produced in those steps end up being owned by `root` instead of the current user.
This causes some problems, eg: when switching branches.
It can be manually cleaned up with `sudo chown -R "$USER" .`
This change makes sure the generated files are owned by the current user instead, avoiding the problem and cleanup.
> Generate files with correct owner

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
> networking doc: typo fixes

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
Issue: https://github.com/istio/istio.io/issues/3313
> Fix api document

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
> Document exportTo restrictions

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
> Update API docs (service entry, gateway, sidecar)

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Resolves https://github.com/istio/api/issues/847
An example Sidecar CRD in networking/v1alpha3/sidecar.proto is invalid.
It's the example that starts at line 77. It is generated into https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/ . If I take that example and use istioctl validate -f the error response is
```
* error validating resource (networking.istio.io/v1alpha3, Kind=Sidecar Name=default Namespace=): sidecar: the egress listener with empty port should be the last listener in the list
```
> Fix example Sidecar structure

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
This is a companion to https://github.com/istio/api/pull/857 targeting `release-1.1`.  It is cherry picked but I had to resolve a conflict.
> .protos should have valid CRDs in comments

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Signed-off-by: Shriram Rajagopalan <rshriram@gmail.com>
> last minute doc fixes

- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
- policy/v1beta1/istio.policy.v1beta1.pb.html
Follow up PR of #789. Context: https://github.com/istio/api/pull/789#discussion_r257339655
> Clearify comment for server_name field in Mixer oop auth config

- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
ns of egress gateway should be istio-system in the context
> ns of egress gateway should be istio-system in the context

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
update host desc that more than one vs share same host to permit the ingress style gateway, that is two  service share the same domain name and delegated by path. 
#870 
istio/istio#12590
> update host desc that more than one vs share same host

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
This fixes a minor styling issue with the `ISTIO_META_USER_SDS` variable in the `Gateway` docs.
Fixes #880.
/cc @esnible
> Fix ISTIO_META_USER_SDS styling in docs

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Fixes https://github.com/istio/istio/issues/12237
> Add warning about sidecar egress

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Both for HTTPFaultInjection.Abort and HTTPFaultInjection.Delay, the docs give an example for a "1 out of every 1000 requests".
The value given in the example to the 'percentage' field is '0.001', but the field 'percentage' is a type 'Percent' which goes from 0 to 100, so '0.001' would mean "1 out of 100000"
I've corrected the value from '0.001' to '0.1' to match "1 out of 1000", was either that or changing the docs to "1 out of 100000", but seemed like a too big number to me ;)
> Correct percentage value to match 1 out of 1000 docs value

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
The destination rule proto default values for `max_retries` ,  `http1_max_pending_requests` and `http2_max_requests` is not as per the current [implemementation](https://github.com/istio/istio/blob/7d61672e25a28b0fa49ef2091f5b49703307572f/pilot/pkg/networking/core/v1alpha3/cluster.go). This PR corrects the docs.
> correct default values in the destination rule

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Simple change to add the default number of max connections to the docs.
ref: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#cluster-circuitbreakers-thresholds
cc: @Stono
> add default max connections to docs

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/network.proto
currently, MeshNetworks  code snippet  is inline
improved it using yaml block
> improve code snippet style of MeshNetworks

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
The default on envoy is to use MAX_STREAMS, defined internally
to be 2²⁹ connections.
This is one of the few properties missing an explanation for its default value.
> Document default behavior for maxRequestsPerConnection

- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
- policy/v1beta1/istio.policy.v1beta1.pb.html
Resolves https://github.com/istio/api/issues/927
> Missing quote in match example

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
commit ab50e4491b613f1ece33f297a7d49c8e5afbb477
Author: Steven Dake <sdake@users.noreply.github.com>
Date:   Fri Jun 14 14:58:20 2019 -0700
Run make after modifying protos
This generates the go commented PI as well as the proto HTML
documentation.
commit 332d1e3a677bf7e4deded524a1a590b690d37541
Author: Steven Dake <sdake@users.noreply.github.com>
Date:   Fri Jun 14 14:56:45 2019 -0700
Modify upstream links that changed in envoy docs
See PR: https://github.com/istio/istio.io/pull/4424/files
This was an emergency blockage during the last few days of release
1.2, so the exact process of modifying API first then modifying docs
was not done.  Instead, sadly it felt backwards (modify docs first,
then modify this repo).
> Fix envoy links

- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
* Correct gRPC usage for RBAC methods field
* Refine TCP and gRPC usage for RBAC
This is a cherry-picking for release-1.2
> Refine RBAC API usage for TCP and gRPC services.  (#942)

- policy/v1beta1/istio.policy.v1beta1.pb.html
- policy/v1beta1/type.pb.go
- policy/v1beta1/type.proto
- proto.lock
- python/istio_api/policy/v1beta1/type_pb2.py
This PR introduces support for STRING_MAP in the policy API for out of process adapters.
Currently STRING_MAP is supported in the in tree adapters but not the out of process adapters. This means that a subset of the Expression Language is not supported via GRPC.
```
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
name: i1logentry
namespace: istio-system
spec:
template: logentry
params:
timestamp: request.time
variables:
...
requestHeaders: request.headers | emptyStringMap()
requestParams: request.query_params | emptyStringMap()
...
```
With STRING_MAP added to the protobuf definition in-process and out-of-process adapters will support the same set of types.
There will be a follow up change to istio/istio to implement STRING_MAP. Draft implementation: …
> Add support for STRING_MAP in policy API

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.proto
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
The `RbacConfig` is wrongly hidden from the doc. Also fixed the comments. This PR also puts the authentication page to be right above authorization page.
> fix RbacConfig comments and do not hide in documents

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
This PR updates the documentation of Gateway.port.protocol so that it matches the list of supported values in Istio 1.2.0.
Right now the documentation is missing the values `REDIS`, `MYSQL` and `UDP`.
> Fix documentation of supported protocols for Port.protocol

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Name is still documented in destination rules for the port, but the field is not documented in portSelector. Attempts to use the field hit (https://github.com/istio/istio/blob/870877a1e3d01f6a2c285f67ed1f709a9f993095/pilot/pkg/model/validation.go#L2257) "Port.name HTTP is no longer supported for destination".
Please provide a description for what this PR is for.
And to help us figure out who should review this PR, please
put an X in all the areas that this PR affects.
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
> Remove reference for name since it fails validation

- tools/protoc/Dockerfile
The old continer builder was based on Golang 1.9 (according to
@geeknoid; I couldn't actually get it to build).  The container
could use some serious simplificaiton.  If we don't need to pin gRPC
and protobuf, it is better practice to let the experts in golang
distribute their own container (golang:1.12) and work from that.
I have assumed in this PR that they have the correct versions of
gRPC and protobuf, which may be a bad assumption.
Also this PR does not yet build (so don't merge) because of a
dependency problem in the tools repo.  Further, this PR likely
won't build and certainly isn't tested yet, until the tools
repo build problem is sorted out.
Depends-On: https://github.com/istio/tools/pull/222
> Simplify protogen container builder

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Related to https://github.com/istio/istio/pull/15609 .
By the PR,  the default value of `min_health_percent` was changed to `0%` from `50%`.
> Follow a comment about the default value of `min_health_percent`.

- Makefile.core.mk
Typing "make" twice would run cue twice because dependencies from *.proto files to *.json files weren't being tracked. Now with the right dependency tracking in place, the second time you run "make" nothing happens because all targets are up to date.
> Fix OpenAPI dependency tracking.

- proto.lock
- python/istio_api/rbac/v1alpha1/rbac_pb2.py
- rbac/v1alpha1/istio.rbac.v1alpha1.json
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
- releaselocks/release-1.1/proto.lock.status
Now we have the new approved `AuthorizationPolicy` in the `security` directory, it's best to remove the out-dated one to avoid confusions.
The corresponding code had been removed in https://github.com/istio/istio/pull/16119.
istio/istio#12394
> remove the out-dated authorization policy

- rbac/v1alpha1/istio.rbac.v1alpha1.json
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
Typo fix for `*`s not displayed correctly because they are treated as italic markers.
> typo fix rbac/v1alpha1/rbac.pb.go

- mcp/Readme.md
The XDS protocol doc link changes, fix the url.
> Fix outdated XDS url link

- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
The sidecar config caused the following error when I applied it.
* sidecar: the egress listener with empty port should be the last listener in the list
> fix the sidecar egress order in the example

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Typo fix for config.proto, this PR is to fix the automatically-generated [PR](https://github.com/istio/api/pull/1071)
> Typo fix for config.proto

- mesh/v1alpha1/network.proto
Description in Network.NetworkEndpoints field fromRegistry is misleading by guiding to use a Kubernetes secret name rather than a kubeconfig filename used as a data key inside the secret.
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
Make-up for #4880 and #1076
> refine NetworkEndpoints fromRegistry field description

- GUIDELINES.md
"Config" is short for "configuration" which confused me for a bit. I
think having a more obvious example will help not distract readers from
the point of this guideline.
> Use different example in api guidelines

- extensions/field_rules.proto
Proposing some extensions for Istio API protos. With these extensions, we are able to specify additional rules to the API fields. e.g.
``` protobuf
message Destination {
...
string subset = 2 [(extension.rules).string.pattern = "^[a-zA-Z0-9](?:[-a-z-A-Z0-9]*[a-zA-Z0-9])?$"];
...
}
```
This will allow us to express richer schema syntax, more docs and better API/client tooling.
> Add istio api extensions definitions

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
- proto.lock
Even with permissive mode, the filter chain adds "require_client_certificate": true" and required you to pass client cert.
@rshriram pls review
> Even with permissive mode, the TLS require client cert

- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
- rbac/v1alpha1/rbac_deepcopy.gen.go
- rbac/v1alpha1/rbac_json.gen.go
Also add full syntax for the YAML value, to remove ambiguity.
> Remove incorrect escape character.

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Note that this is slightly different than the annotation originally decided in https://docs.google.com/document/d/1r1hOBIwkDesZ8vYaHMj2YThEcUxegB-fLMPBst_yXIU/edit#heading=h.xw1gqgyqs5b. Originally the annotation was called `galley.istio.io/noanalyze`, but I was worried that the name itself might be potentially confusing (for example, the presence of this annotation appears to imply that the resource is never analyzed, rather than a specific list of codes).
Due to this change i've added approvers from the doc as approvers on this PR as well.
> Add annotation for suppressing analyzer messages per-resource

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
To support the downgrade scenario to istio 1.4. 
fixes: https://github.com/istio/istio/issues/20861
> Use v1alpha3 as the storage version for networking APIs

- authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
- kubernetes/customresourcedefinitions.gen.yaml
This is replaced by security/v1beta1/peer_authentication.proto
> Deprecate authentication alpha policy

- Makefile.core.mk
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/proxy.pb.go
Fixes https://github.com/istio/istio/issues/21794. Regular yaml unmarshal doesn't work with MeshConfig because json struct tags are rendered as snake_case by protoc.
> Fix MeshConfig field tags for JSON unmarshal

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/proxy.pb.go
- operator/fixup_structs/main.go
- operator/v1alpha1/component.pb.go
- operator/v1alpha1/operator.pb.go
https://github.com/istio/api/pull/1301 introduced a bug where some fields are not converted from snake to camel case because the regex expected at most a single underscore - so fields like my_long_named_field would not match it.
> Fix bug with JSON tag camelCase conversion

- operator/fixup_structs/main.go
- operator/v1alpha1/component.pb.go
- operator/v1alpha1/operator.pb.go
Manual cherry pick of https://github.com/istio/api/pull/1324.
https://github.com/istio/api/pull/1301 introduced a bug where some fields are not converted from snake to camel case because the regex expected at most a single underscore - so fields like my_long_named_field would not match it.
> [1.5] Fix bug with JSON tag camelCase conversion (#1324)

- label/label.go
This PR adds a new package that holds definitions for labels used by Istio.
This was a FR from the knative team. The request is to have a common package for these definitions that can be used without taking a dependency on the `istio/istio` repo (dep already exists to `istio/api`).
The values are taken, initially, from [Pilot code](https://github.com/istio/istio/blob/2d1b8d6fc2a30787d397770e6f6aa1eec6a46b03/pilot/pkg/model/service.go#L136-L155).
These are not placed in the `annotation` package, as they are not resource annotations. It is possible that we will want to expand the package to include docs generation similar to `annotation`, but for now that is not part of the initial request.
Signed-off-by: Douglas Reid <dougreid@google.com>
> feat(label): add label package

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Adding spaces to correct `yaml` examples
> Fix comment indent

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/workload_entry.pb.go
- networking/v1alpha3/workload_entry.proto
- networking/v1beta1/workload_entry.pb.go
- networking/v1beta1/workload_entry.proto
Currently the workload entry is generating an invalid CRD as its trying
to store both alpha and beta - it should just be one. I also added an
extra column to print out the address
For https://github.com/istio/istio/pull/22472
> Fix WorkloadEntry CRD

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
As mentioned in https://github.com/istio/istio/pull/23559#issuecomment-624412699, the field is causing validation failure in EnvoyFilter. Will create a follow up PR to add such field for EnvoyFilter.
Also remove from `handler` and `instance` where google.protobuf.Struct exists in their fields.
> Remove preserveUnknownFields from EnvoyFilter

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
Envoy Filter's the 2th yaml configure has a  indentation error:
```
error: error parsing lua.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key
```
> fix envoy filter doc indentation error

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
In this PR, we change the block of CORS Policy definition from `allowOrigin` to `allowOrigins` so not to be misleading for people who take this example as guide to setup their meshes.
After the upgrading to Istio 1.6, the block with deprecated `allowOrigin` is not respected thus not working.
https://github.com/istio/istio/issues/24145
> CORS Policy Example: Change allowOrigins block

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
The scope of label search is not only restricted to the configuration namespace in which the Gateway resource is present, the current comment may confuse users.
> doc: correct the comment of Gateway

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Related to https://github.com/istio/istio/pull/23941 and in preparation for a matching CNI PR, this change defines the new `includeOutboundPorts` annotation that is ultimately used by `istio-iptables`.
> Add includeOutboundPorts annotation

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Follow up PR for https://github.com/istio/api/pull/1489
Based on @costinm https://github.com/istio/api/pull/1489#issuecomment-651142386  , I have updated all other defaults as per the latest [DefaultMeshConfigs](https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh.go#L80). 
Suggestions are welcome to improve default value descriptions as it will reflect on [istio.io docs](https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig). 
Ref: https://github.com/istio/istio/pull/22687
> Specify defaults for mesh and proxy configs

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
We need to keep to keep the unknown fields inside EnvoyFilter, as the current schema is not a comprehensive validation for the value field.
> Add preserveUnknownFields to EnvoyFilter

- mixer/v1/mixer.proto
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
- policy/v1beta1/istio.policy.v1beta1.gen.json
- policy/v1beta1/istio.policy.v1beta1.pb.html
As part of https://github.com/istio/istio/issues/25381
Happy to change "A list" to "An allowlist" if it improves clarity. Didn't want to be redundant
> Replace/remove "whitelist" in comments/descriptions

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- networking/v1beta1/sidecar.gen.json
- proto.lock
Updates the comment for CredentialName in DestinationRule API to clearly specify use case is for originating traffic from gateway proxy type only.
Ref: https://github.com/istio/istio/issues/14039
> Add Comment to CredentialName explaining use with Gateway Proxy only

- meta/v1alpha1/status.pb.html
- meta/v1alpha1/status.proto
This instruction is causing test failures for the docs folks.
> remove hide from docs instruction in meta/status

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
None of the other links use latest so this is making this link like the others. There is code in istio.io that adds the `latest` into the link at a later point.
> Fix link so istio.io linter passes (remove latest)

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
Gateway API doc update to include information about storing CA certs in a separate secret named `<secret>-cacert`
This is documented in the [Secure Gateways - Configure a mutual TLS ingress gateway task](https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway) (see last line), but not in the API docs.
> Gateway CA certs can be stored in secret-cacert

- security/v1beta1/authorization.pb.html
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/request_authentication.pb.html
- type/v1beta1/istio.type.v1beta1.pb.html
- type/v1beta1/selector.proto
This was reported multiple times on istio.io docs. This PR fixes the workload selector to redirect it to a valid link. 
Related issues:
https://github.com/istio/api/issues/1511
https://github.com/istio/istio.io/issues/7203
https://github.com/istio/istio.io/issues/6877
https://github.com/istio/istio.io/issues/6921
> Fix invalid link for WorkloadSelector

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
Sending PR https://github.com/istio/api/pull/1537 again with both versions updated.
> Gateway CA certs can be stored in secret-cacert. Take 2

- security/v1beta1/authorization.pb.html
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/request_authentication.pb.html
- type/v1beta1/selector.proto
The original PR https://github.com/istio/api/pull/1540 appended `#WorkloadSelector` twice in the generated protobufs.
This PR removes it because `#WorkloadSelector` automatically gets appended in generated protobufs so no need to include it in `$location`.
Suggested by @brian-avery  https://github.com/istio/api/pull/1548#discussion_r458866256 
I think we can close cherry-pick https://github.com/istio/api/pull/1548 and the new one will be created once this is merged in master?
> Fix broken link for WorkloadSelector

- envoy/config/filter/http/authn/v2alpha1/config.proto
- python/istio_api/envoy/config/filter/http/authn/v2alpha1/config_pb2.py
We add trust domain alias, in the mesh config. The authentication filter requires corresponding change to allow a list of TD's from peer request.
[Alias doc](https://docs.google.com/document/d/1ncrENtF6PBVZVjhYePbvZ6F1obbNApKJh5mUDRvwHMw/edit#heading=h.zccr9pxvbieb), approved, in 2019, section "Use of TrustDomainAliases in Authentication Filter Config" clearly document what needs to be done, what this PR is about.
> Add allowed_trust_domains for the authn filter config.

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
Shows up wrong today: https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway
> Fix escape in gateway docs

- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
To fix https://github.com/istio/istio.io/issues/8140
See https://istio.io/v1.5/docs/reference/config/installation-options/ 
> Installing Istio with Helm is deprecated, however, you can use Helm configuration options when installing Istio with istioctl by prepending the string “values.” to the option name.
> Update url for helm installation options

- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
It is now possible to use exportTo to export to specific
namespaces. Was fixed in https://github.com/istio/istio/pull/24443
> Remove note about restriction on exportTo

- security/v1beta1/request_authentication.gen.json
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Fix typo in request authn v1beta1.
From
`If will reject a request if the request contains invalid authentication information`
To
`It will reject a request if the request contains invalid authentication information`
> Fix typo in  request authn v1beta1

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1#ProxyConfig
Some of the inconsistencies.
drainduration_ 
terminationdrainduration
–service-cluster
–service-node
Related:
https://github.com/istio/api/pull/1642
https://github.com/istio/api/pull/1641
> Fix inconsistent rendering of enum constant and code examples for ProxyConfig

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
our default attempts is 2.  We didn't say it earlier because it depends on the value of http timeout.  Now timeout is disabled by default, the default retry attempts should be clear to our users.
> clarify http retry attempts

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Updated:
Turned out doc is correct, our code comment is wrong, I'll open a PR to correct it.   A minor update on drain, thanks to @ramaraochavali for helping me clarify things.
--------
We are having it disabled by default:
https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L480
Also, from my envoy sidecar default config:
```
"stream_idle_timeout": "0s",
```
> Idletimeout clarification

- networking/v1alpha3/sidecar.gen.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.gen.json
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
Implementation PR: https://github.com/istio/istio/pull/28178
This adds an additional allowed value to the sidecar API to facilitate
applications listening on their Pod IP. For example, to run zookeeper,
a user would configure a sidecar:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
name: zk
spec:
ingress:
- port:
number: 3888
protocol: TCP
name: election
defaultEndpoint: 0.0.0.0:3888
egress:
- hosts:
- "*/*"
```
> Add support for Pod IP listener

- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
It also romoves the foo response header -> It also removes the foo response header
> typo in virtual-service docs

- Makefile.core.mk
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/request_authentication.pb.html
- type/v1beta1/selector.pb.html
- type/v1beta1/selector.proto
For https://github.com/istio/api/issues/1700, tested locally it now links to the correct workload selector (not the one used in sidecar) for security API. 
(Will send another PR in istio.io to show the `Common type` in the sidebar)
> link to the correct workload selector used in security API

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
Also resolves https://github.com/istio/istio/issues/28189
Making sure server-side apply keeps the `preserveUnknownFields` field during upgrade.
/cc @richardwxn
> Enforce preserving unknown fields in EnvoyFilters

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Since it is already in our user [doc](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#customizing-trace-sampling), it makes sense to have this reflected in our generated API doc. 
Also, the default was wrong.
> update sampling doc

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/network.proto
The example for MeshNetworks in the [documentation page](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshNetworks) doesn't seem to be correct. The generated pb.go file looks like this:
https://github.com/istio/api/blob/11df83b4d252c9eee246fc26aaa5d4fc2e0acd78/mesh/v1alpha1/network.pb.go#L327-L331
> Fix MeshNetworks example documentation

- Makefile.core.mk
Workaround https://github.com/golang/go/issues/43994
Run tidy after download
> Workaround golang bug causing make gen to fail

- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
subzone: has been around for a while. It's tested and I believe some folks are using it in production. Probably at least beta.
network: fundamental label used by multicluster in particular for configuring multi-network scenarios. Since multicluster as a feature is beta, it makes sense that the stability here matches.
> Updating initial stability of subzone and network labels

- Makefile.core.mk
- buf.yaml
- common/Makefile.common.mk
- prototool.yaml
Following up on #1833, this uses `buf` for linting instead of `prototool`.
A couple changes are made:
- `prototool` lint configuration is deleted, as it is not used anymore, and lint configuration remaining in `prototool.yaml` could lead to confusion as to where the SOT is for Protobuf lint configuration. It looked like the ignores were out of date as well.
- `common-protos` is added to `excludes` in `buf.yaml`. This is more a bug fix - since `common-protos` is symlinked into the base of the repository, we want `buf` to ignore `common-protos` altogether for `buf` to work out of the box. This makes `buf` file discovery ignore `common-protos`, and all `buf` commands work now assuming the symlinks are set up (which `make` does). As a fun example:
```
$ buf build --exclude-imports …
```
> Use buf for protobuf linting

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
Spell check.  Shows up in user facing docs at https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation
> Typo: entirity for entirety

- operator/v1alpha1/deepcopy.go
gofumpt was added to provide extra Golang file formatting.
In the istio/api repo we do minimal checking as most files are generated. However, one un-generated file needs to be updated.
> gofumpt operator/v1alpha1/deepcopy.go

- Makefile.core.mk
#1863 updated the `lint-protos` take in the common directory. Of course a common-files change will overwrite the change in that PR and that cause a lint failure. See #1872.
This PR makes the lint-protos change local to istio/api so a later common-files update regressing the file here will have no effect.
> Update to use local-lint-protos

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
Since we no longer allow users to enable mixer in default istio.
> clean up mixer reference in sidecar API

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Similar to https://github.com/istio/api/pull/1907
Other `kubectl explain kind` are also have a broken links.
```
$ k explain Gateway.spec
KIND:     Gateway
VERSION:  networking.istio.io/v1beta1
RESOURCE: spec <Object>
DESCRIPTION:
Configuration affecting edge load balancer. See more details at:
https://istio.io/docs/reference/config/networking/gateway.html
```
```
$ k explain WorkloadGroup.spec
KIND:     WorkloadGroup
VERSION:  networking.istio.io/v1alpha3
RESOURCE: spec <Object>
DESCRIPTION:
Describes a collection of workload instances. See more details at:
https://istio.io/docs/reference/config/networking/workload-group.html
```
> Fix broken links for locations

- security/v1beta1/peer_authentication.gen.json
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
Adding validation would be better, but in either case, the documentation should make that requirement clear.
Ref:
https://istio.slack.com/archives/C37A4KAAD/p1615592450286300
> Add info about `portLevelMtls` requirement of workload selector with PeerAuthentication

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Allows customers to dry-run an authorization policy to test the effect using real traffic without enforcing the policy, reducing the risk of creating or changing the authorization policy. 
Only supports AuthorizationPolicy for now, the admission controller will reject other resources with the dry-run annotation.
Design doc: https://docs.google.com/document/d/1xQdZsEgJ3Ld2qebfT3EJkg2COTtCR1TqBVojmnvI78g (approved by Security WG)
> add dry-run annotation

- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Discussed offline and decided to keep the ext-authz in experimental in 1.10 to give us more time to address other issues.
cc @nrjpoddar @howardjohn @duderino
> change ext-authz feature to experimental

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
These are not new annotations, but backfilling ones used in injection
that were not previously in the API repo.
> Document annotations used for injection

- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Since these variables are supposed to refer to the yaml config, I believe they should be the camel cased names, not the pb struct names.
```release-note
NONE
```
> Change snake_case to camelCase for yaml documentation

- envoy/config/filter/http/authn/v2alpha1/config.proto
Note: This only changes the internal authn filter to allow opt-out of the JWT claim based routing feature (see https://github.com/istio/proxy/pull/3477).
This is NOT end-user facing API and does not change the Istio CRDs at all.
@kyessenov @bianpengyuan @mandarjog @lambdai
> add disable_clear_route_cache to the internal authn filter config

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/jwt.gen.json
- security/v1beta1/jwt.pb.go
- security/v1beta1/jwt.pb.html
- security/v1beta1/jwt.proto
- security/v1beta1/request_authentication.gen.json
This patch fixes the use of jwtHeaders as a field in the example (there is no `jwtHeaders` field). This is tipped by an issue comment here: https://github.com/envoyproxy/envoy/issues/11672#issuecomment-653404950. This also fixes some of the typos.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>
> docs: Use fromHeaders instead of jwtHeaders field in JWTRule example

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
This PR changes the format of the special header used for JWT claim based routing in virtual service from `x-jwt-claim...` to `@request.auth.claims...`:
1. The use of the `@` makes the header name drastically different from a normal real HTTP header. This change is made to:
- Prevent possible customer confusion of the special header name with real HTTP headers, and any security and usability issues caused by the confusion.
- Prevent potential collision with existing values because a customer might already be using the same header in the virtual service.
The `@` makes it invalid for HTTP header which is intentionally to make sure it is never used by customer before and will never collide with existing HTTP headers. For example, Envoy and google.com will simply reject the header using `@` …
> update jwt based routing

- networking/v1beta1/proxy_config.proto
Previously, the defined merge semantics with multiple PC CRs in the same namespace or matching the same workload was to merge with no guaranteed precedence. This does not align with other Istio CRs: usually, we document that it's only valid to have 1 workload / namespace and then take the oldest.
> Align ProxyConfig merge semantics with other Istio resources

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1beta1/workload_group.pb.go
- networking/v1beta1/workload_group.proto
- releasenotes/notes/workloadgroup-v1beta1.yaml
Looks like v1beta1 workload entry drops storageVersion... this should fix automator failures. 
https://github.com/istio/istio/pull/36754
> fix storageversion for workload group

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
This is the recommended method for 6 releases now. There is still one
reference to the file mount option.
> Move more examples to `credentialName`

- go.mod
- operator/fixup_structs/main.go
Had to update go version:
```
operator/fixup_structs/main.go:200:72: 0o/0O-style octal literals requires go1.13 or later (-lang was set to go1.12; check go.mod)
```
> lint updates needed for common-files updates

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
the original demo will be rejected:
```console
ACK ERROR httpbin-74fb669cc6-tpjfh.default-4 Internal:Error adding/updating listener(s) virtualInbound: Error: terminal filter named envoy.filters.http.router of type envoy.filters.http.router must be the last filter in a http filter chain.
```
> update envoyfilter EXTENSION_CONFIG demo

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
The example had a wrong yaml file with workloadSelector under metadata.
> Fix workloadSelector example in DestinationRule

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
RFC: [Simplify sidecar egress mTLS](https://docs.google.com/document/d/1UXpT3rZpE2uFeMh5KffAZAPAoZBLNSHc/)
Implementation PR: https://github.com/istio/istio/pull/38324
The description for credentialName attribute in DR needed a little bit of modification to clarify the newly added behaviour.
> Support CredentialName configuration in DR for sidecars

- extensions/v1alpha1/wasm.gen.json
- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
This PR proposes to hide `verification_key` field from documentation, and declare that the field will be not implemented until the detailed design is elaborated.
In current situation, there are two major stream for signing/verifying the OCI image. On the other hand, it seems to be no apparent major stream for signing and verifying Wasm binary. 
In this case, we can think of more generalized API interface to deal with such multiple mechanisms, and it need to be designed more general way rather than providing just a `verification_key` field.
Therefore, I would like to propose to hold this field at this time and get it back later.
cc: @dgn @mathetake @PiotrSikora @mandarjog @bianpengyuan
> Hide verification_key from documentation

- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
URL: https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry-Resolution
ServiceEntry.Resolution description for `DNS_ROUND_ROBIN` does not
wrap `DNS_ROUND_ROBIN` in Markdown backticks, causing the keyword to
show up as italicized DNS<em>ROUND</em>ROBIN due to the underscores.
This change wraps `DNS` and `DNS_ROUND_ROBIN` in backticks, avoiding
this rendering issue.
Also added a comma in the description.
> Fix API rendering issue in ServiceEntry.Resolution

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>
It's just an update of `TunnelSettings` documentation. For more context, take a look at this [comment](https://github.com/istio/istio/pull/37968#discussion_r872522202).
> Require uppercase value of tunnel protocol

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Thanks to @davidhauck 
There was a rendering problem at https://preliminary.istio.io/latest/docs/reference/config/networking/destination-rule/
where most of the content was missing, due to a missing tabset in the document.
> Fix broken DR documentation

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Since the load balance LEAST_CONN is deprecated, it's better to fix the description of load balancing algorithms applicable to warmup.
> Fix description for warmup.

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- releasenotes/notes/39157.yaml
New namespace annotation used to configure leader(s) for remote clusters.
See https://github.com/istio/istio/pull/39406
> Namespace annotation for cluster leaders

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
This has been replaced with a label of the same name. The label is
strictly more powerful since selection is done in Kubernetes, rather
than in Istio.
See https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy for documentation on the new label.
This change simply makes `istioctl analyze` report an info warning. https://github.com/istio/istio/pull/32959 is added to enhance the message to make it more clear. 
This does not change the runtime behavior, nor imply the annotation will be removed at any time.
> Deprecate injection annotation

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
auto-san-validation feature was introduced in 1.14 release. Enhancing the subject_alt_names description a bit to clarify the behaviour.
> Add auto-san-validation documentation

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Clarify Destination Rule docs that Max Pending Requests/ Max Requests apply to both Http1 and Http2
See https://github.com/istio/istio/issues/31548 and https://github.com/envoyproxy/envoy/pull/9668 (See version history and doc updates)
> clarify destination rule docs

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/sidecar.gen.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.gen.json
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
The bind attribute already works with IPv6, but somehow
the documentation seems to be not updated.
> Update sidecar bind description to include IPv6

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.proto
Fix the comments describing the workload mode of Gateway.
To have consistency with the existing Telemetry API, we have changed the semantics of Workload mode in Gateway, but there was an omitted comments which had to be changed as well.
> Fix the comments explaining Workload mode of gateways

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
The ConfigSource.address field mentions that the MCP backend address can be an IP address but doesn't clarify the protocol that needs to be used (xds:// or k8s://) in the docs.
Just adding a line to the doc to make it clear in the docs so that people don't have to dive into the code to see the possible address formats
> Update ConfigSource.address examples in docs

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
I noticed this reference to an unrelated example that was [copied verbatim](https://github.com/istio/api/pull/1331) from `workload_entry.proto` while reading the docs at https://istio.io/v1.15/docs/reference/config/networking/service-entry/.
> Remove remnants of old example in ServiceEntry docs

- extensions/v1alpha1/wasm.gen.json
- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- kubernetes/customresourcedefinitions.gen.yaml
Added in https://github.com/istio/api/pull/2412
Implemented by https://github.com/istio/istio/pull/40862
This removes the hide_from_docs annotation to expose the documentation for traffic selector.
> remove hide_from_docs for traffic selector

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- releasenotes/notes/fix-destinationrule-doc.yaml
The Destination Rule documentation show that the verify cert at client environment variable name is `VERIFY_CERT_AT_CLIENT` in [ClientTLSSettings](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings) but according to the [pilot-discovery](https://istio.io/latest/docs/reference/commands/pilot-discovery/) docs the environment variable is `VERIFY_CERTIFICATE_AT_CLIENT`.  Updating the Destination Rule documentation to use the correct environment variable name.
> Update DestinationRule docs with correct env variable name

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
refer: https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats
associate to: https://github.com/istio/istio.io/pull/12357
1. Istio uses `outlier_detection` for `circuit_breakers`
2. There are 6 retry metrics (`cluster.<name>.upstream_rq_retry*`) 
3. There are many upstream connections metrics (`cluster.<name>.upstream_cx_*`) 
4. Added `upstream_rq_timeout` suffixed example
> fix: envoy statistics config documentation

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Now that OpenTelemetry Tracing is working in 1.16.1 we should add it to the documentation.
Signed-off-by: blakeromano <blakeromano19@gmail.com>
> Add OpenTelemetry Tracing Provider to Docs

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>
To avoid confusion like in this [issue](https://github.com/istio/istio/issues/32041), I think it's worth to clarify that `Sidecar` is not applicable to gateways. Users may guess that `Sidecar` should work for gateways, because both gateway and sidecar proxies are the same istio-proxy.
> Clarify that Sidecar is not applicable to gateways

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
[ServerTLSSettings](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) seem to have documented this already.
> Clarify credentialName usage in ClientTLSSettings for separate ca secret

- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
The double asterisks currently cause the text to be italicized instead of showing as expected
> VirtualService docs minor formatting fixes

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
`inlineCode` has been deprecated in upstream envoy https://github.com/envoyproxy/envoy/pull/22125. This can be replaced with `defaultSourceCode` which is not deprecated.
> update deprecated field in EnvoyFilter example

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
small update to the docs for the `credentialName` field. Main change is referring to the secret as Opaque instead of `generic` (the kubectl subcommand).
> update credentialName docs for DestinationRule and Gateway

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
As per : https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh.go#L92 this is enabled by default.
Better to clarify this in docs, because k8s has this disabled by default, and caused us come confusions while we started using this. Ideally this should have been disabled by default.
> Clarify that MeshConfig.localityLbSetting is enabled by default

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Introduced in https://github.com/istio/istio/pull/44174 and causes a `istioctl analyze` `Unknown Annotation` errors:
```
"Warning [IST0108] (Deployment default/bookinfo-gateway-istio) Unknown annotation: gateway.istio.io/controller-version
Warning [IST0108] (Pod default/bookinfo-gateway-istio-7f4d8dd7f6-cvg9d) Unknown annotation: gateway.istio.io/controller-version
Warning [IST0108] (Service default/bookinfo-gateway-istio) Unknown annotation: gateway.istio.io/controller-version"
```
I believe this should fix the issue, but this is my first time working with annotations. I believe we would keep this hidden and it seems most annotations are Alpha.
> Add gateway.istio.io/controller-version annotation

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
The docs incorrectly mentioned CLIENT as INBOUND and SERVER as OUTBOUND in the traffic selector field docs in WASM Plugin. This PR changes the order of OUTBOUND and INBOUND terms to fix this confusion. 
The `WorkloadMode` docs correctly mention the CLIENT as OUTBOUND and SERVER as INBOUND: https://istio.io/latest/docs/reference/config/type/workload-selector/#WorkloadMode
> docs: fix wasm plugin traffic selector docs

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
This has come up a couple of times (https://github.com/istio/istio.io/issues/7622, https://github.com/istio/istio/issues/44424), so it makes sense to be explicit in the docs with an example.
> updating header presence explanation with example

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.pb.html
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.gen.json
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
This fixes #2774.
1.2.3.4 currently belongs to APNIC Debogon Project, which means that it is currently unallocated but may be allocated in the future. For documentation purposes RFC5737 allocates 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and 203.0.113.0/24 (TEST-NET-3). Documentation in proto files should use one of these addresses instead.
> Replace 1.2.3.4 with RFC5737 address (#2774)

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Compromise to https://github.com/istio/api/pull/2539, to prefer over the bootstrap EnvoyFilter.
@zirain
> stats: allow custom histogram buckets

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
The prefix is on statsd name, not prometheus name, based on testing.
> clarify the documentation

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.pb.html
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
dry-run is a very useful feature, but there is no mention in the authz reference document, so add an example.
> Add authz dry-run example

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- releasenotes/notes/2871.yaml
xref: https://opentelemetry.io/blog/2023/sunsetting-opencensus/
> mark opencensus deprecated

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
I think this is the default mode, based on this.
https://github.com/istio/istio/blob/575e7a1087351d02325cca814c2fbc9cad0f0ad7/cni/pkg/plugin/redirect.go#L36
> add a note about the default inbound interception mode

- security/v1/request_authentication.pb.go
- security/v1/request_authentication.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
from v1.19, support using `[]` as a separator for nested claim names. see https://github.com/istio/istio/pull/44355
> fix JWT claim based routing doc

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
Some folks communicated that they were confused about how `attempts` could impact the maximum number of requests made.
> Update virtualservice HTTPRetry docs for the `attempt` field

- Makefile.core.mk
- buf.gen.yaml
- cue.yaml
- gen.sh
- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
- security/v1/jwt.pb.go
- security/v1/jwt.proto
- security/v1beta1/jwt.pb.go
- security/v1beta1/jwt.proto
For https://github.com/istio/istio/issues/46151
Based on https://github.com/istio/api/pull/2946, will rebase once that merges
This PR moves our CRD generator from cue-gen to protoc-gen-crd. The details of these don't matter too much; the final generated CRD.yaml does. The migration value is not really exposed in this PR, as I tried to keep it minimal; a followup PR will be used where we implement https://github.com/istio/istio/issues/46151 (likely multiple PRs, to keep it small). For now, the following changes are present:
* REQUIRED fields are actually required. I validated each field that is currently set as REQUIRED is marked as required in the webhook, so this is not a breaking change
* The `oneOf` representation is simplified. In my testing, I have found these to be equivalent in …
> Migrate to protoc-gen-crd

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
looks like envoy dumped all the api-v2 docs
old link: https://web.archive.org/web/20210421173338/https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-enum-config-filter-network-http-connection-manager-v2-httpconnectionmanager-forwardclientcertdetails
new link: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-forwardclientcertdetails
> fix broken envoy docs link

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
The property name that users should use is `ignoreUriCase`.
closes istio/istio.io#14072
> Subject: update doc for ignoreUriCase

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
The URLs weren't rendered correctly in the docs.
> docs: fix a typo and incorrect rendering of URLs

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
The current `selector` comments of PeerAuthentication doesn't explain whether the selector in root namespace will select all workloads in all namespaces like  `RequestAuthentication` and `AuthorizationPolicy`. So make it clear.
> align `selector` comments of PeerAuthentication with `RequestAuthentication` and `AuthorizationPolicy`

- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
For the consistency/readability sake, updating all instances of "k8s" in the comments to "Kubernetes".
> docs: use Kubernetes instead of k8s in the proto field comments

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Minor formatting fixes (i.e. `backticks`) and fixing the field name in the doc.
> docs: field name and minor formatting fixes

- kubernetes/customresourcedefinitions.gen.yaml
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
Minor formatting fixes, typos, and adding a link or two as references.
> docs: fix formatting issues, typo, add links

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
Add a couple of notes to the AuthorizationPolicy and PeerAuthentication docs about the ports field and how they refer to the workload/container ports, not Kubernetes Service ports. (ref: https://github.com/istio/istio/issues/49098)
> docs: add notes for ports used in AuthPolicy/PeerAuth

- scripts/breaking.sh
After getting the latest master, I couldn't do the `make gen` task anymore. 
```
./scripts/breaking.sh: line 29: cd: api: No such file or directory
make[1]: *** [Makefile.core.mk:53: breaking] Error 1
make: *** [Makefile:44: gen] Error 2
```
@howardjohn helped me figured out the problem, sending this fix PR :)
> Fix cloned path in breaking task check

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
ref: https://github.com/istio/istio/issues/49829
> add some annotations for ambient traffic redirection 

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Related to https://github.com/istio/istio/pull/50365
Part of https://github.com/istio/istio/issues/16585
> Add docs and examples for path templating

- networking/v1beta1/proxy_config.pb.go
- networking/v1beta1/proxy_config.proto
Part of [173](https://github.com/istio/enhancements/issues/173)
ProxyConfig was not promoted to v1. Stable channel is v1 only.
> Add extended release channel flag to ProxyConfig

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1/request_authentication.pb.go
- security/v1/request_authentication.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
- telemetry/v1/telemetry.pb.go
- telemetry/v1/telemetry.proto
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.pb.html
- type/v1beta1/selector.proto
Previously, only a Gateway resource was defined as a supported attachment type. This PR updates the API docs to include a Service as a supported type and also fixes an incorrect link to Gateway API documentation.
> Adds Service Type to PolicyTargetReference API Docs

- networking/v1/virtual_service.pb.go
- networking/v1/virtual_service.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
Fixes https://github.com/istio/api/issues/1931
> virtual service: minor grammar fix

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Noticed a typo in the docs formatting after reading about the new [Path templating in Authorization Policy](https://istio.io/latest/news/releases/1.22.x/announcing-1.22/#path-templating-in-authorization-policy) feature
Fixing the api doc so that it can also be fixed on the website
> Fix typo in closing tag for some code blocks

- GUIDELINES.md
Adds guidelines for adding a new feature to a `v1` API or adding a new API to ensure that the stable validating admission policy is kept up to date. 
Part of [173](https://github.com/istio/enhancements/issues/173)
> add guidelines for adding new features to stable APIs

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
This is a manual cherry-pick of #3196 since the automated one #3213 requires `make gen` to be run
>  [release-1.22] Fix typo in closing tag for some code blocks

- kubernetes/customresourcedefinitions.gen.yaml
- tests/testdata/wasm-invalid.yaml
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.proto
This gives WasmPlugin and Telemetry full parity with the webhook.
Verified by fuzzing, which I will merge into istio/istio after this
(tests fail before this lands)
Related: https://github.com/istio/istio/pull/51287
> Improvements to CEL validations

- networking/v1beta1/proxy_config.pb.go
- networking/v1beta1/proxy_config.pb.html
- networking/v1beta1/proxy_config.proto
Based on istio/istio#43865, concurrency will only be auto determined based on cpu limits (no requests)
> Fix concurrency docs

- security/v1/peer_authentication_alias.gen.go
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
Given we seem to have decided to keep `PeerAuthentication` around in ambient mode, update the docs to remove the warning, and add the caveat you can't `DISABLE` mTLS any more.
(This may or may not be the project's decision.)
> Update PeerAuthentication docs

- kubernetes/customresourcedefinitions.gen.yaml
- meta/v1alpha1/status.pb.go
- meta/v1alpha1/status.proto
int64 in proto is encoded to json as a string. To support this, we make
it accept either form.
Without this, istio fails to write the status. See
https://github.com/istio/istio/pull/52159.
Note: this is only an issue now since we just added schema validation
for status.
> Make observedGeneration intOrStr

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- networking/v1/sidecar_alias.gen.go
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar_alias.gen.go
This is a bit of a mess since its documented in 3 places * 2 resources.
Meaningful changes:
* Explain registry only != security
* Remove recommendation to use registry_only, but explain why someone
might
> Improve OutboundTrafficPolicy docs

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
> Service  with `""`
The wording doesn't explicitly mention that it's `group: ""`. This makes it very clear, as well as mentions you can write `"core"` as well. 
https://github.com/istio/istio/blob/d7a9700d5eaa4e9728274b408623670f48deadb5/pilot/pkg/model/policyattachment.go#L133-L140
> docs: clarify target ref to service

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Correct typo from 'overriden' to 'overridden'.
Fixes https://github.com/istio/istio.io/pull/15562#issuecomment-2290904741
> Fix minor typo

- kubernetes/customresourcedefinitions.gen.yaml
- meta/v1alpha1/status.pb.go
- meta/v1alpha1/status.proto
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/workload_entry.pb.go
- networking/v1alpha3/workload_entry.proto
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.proto
- networking/v1beta1/proxy_config.pb.go
- networking/v1beta1/proxy_config.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.proto
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.proto
Fixes https://github.com/istio/istio/issues/52749
> Pick up changes to CRD template naming and fix excessive WG validation

- networking/v1/virtual_service_alias.gen.go
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service_alias.gen.go
seeks to add clarification around case-sensitive vs case-insensitive options for stringMatch in the VirtualService API
> clarify documentation around stringMatch and case-sensitivity

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
This PR is clarifying the default value of ForwardClientCertDetails which is SANITIZE_SET for GW (and not SANITIZE as previously stated) and APPEND_FORWARD for sidecar proxies (as written here https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyHeaders).
> Clarify ForwardClientCertDetails comments

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.proto
- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
- security/v1/authorization_policy_alias.gen.go
- security/v1/request_authentication_alias.gen.go
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.proto
- telemetry/v1/telemetry_alias.gen.go
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.proto
- tests/testdata/reqauth-invalid.yaml
Per
https://gateway-api.sigs.k8s.io/geps/gep-2648/?h=targetrefs#multiple,
only 16 max allowed -- which is quite reasonable.
Additionally, consistently allow only workloadSelector OR targetRef; we
had this only on some types
> Improve validation for targetRefs

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Stop saying we "block" or "allow" traffic; its not true.
> sidecar: fix misleading docs

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
Fixes https://github.com/istio/istio/issues/43437
Fixes https://github.com/istio/istio/issues/51575
> Codify labels and annotations that have been added directly to istio/istio

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1/service_entry_alias.gen.go
- networking/v1/workload_group_alias.gen.go
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.proto
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.pb.html
- networking/v1alpha3/workload_group.proto
- networking/v1beta1/service_entry_alias.gen.go
- networking/v1beta1/workload_group_alias.gen.go
- tests/testdata/serviceentry-invalid.yaml
- tests/testdata/serviceentry-valid.yaml
- tests/testdata/workloadgroup-invalid.yaml
- tests/testdata/workloadgroup-valid.yaml
This continues the trend of adding CEL validation by adding WG support and some of SE (it got too much, so wasn't able to complete it)
> Add CEL validation to SE and WG

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Added in https://github.com/istio/istio/pull/53435
> Add traffic distribution annotation

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
The user might be confused about the usage of `subjectAltNames`, trying to use it to add more hostnames to an endpoint.
Make clear that it requires TLS mode mutual, and the the alternative names are those presented by the client for authentication.
Originally proposed as a docs contribution:
https://github.com/istio/istio.io/pull/15733
but the docs are autogenerated from this repo.
> Improve documentation for subjectAltNames

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
The existing wording made it appear (to me at least) that the annotation was deprecated in favour of itself.
> Clarify that while this annotation has been deprecated, the label of the same name is still available.

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Now the refdocs builder is running again, it has uncovered a missing / introduced in #3308 which is now breaking lint of istio docs.
> add missing slash to fix docs path/lint

- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
There was a typo in the generated files for labels that I noticed when working on istio/istio. Came here to fix the typo and regenerate the files.
> noticed typo in labels gen proto link in description note

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
I couldn't see any explanation of what the '~' character does for this annotation , but it seems like it is supposed to set visibility to nothing: 
https://github.com/istio/istio/blob/055e235292052c100688def4bee9c63b3fab830c/pilot/pkg/serviceregistry/kube/conversion_test.go#L305
https://istio.slack.com/archives/C37A4KAAD/p1728324326776739?thread_ts=1728036926.260279&cid=C37A4KAAD
> doc: Adds explanation of the '~' character to networking.istio.io/exportTo annotation

- GUIDELINES.md
- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.proto
- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1/destination_rule_alias.gen.go
- networking/v1/service_entry_alias.gen.go
- networking/v1/workload_entry_alias.gen.go
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/workload_entry.pb.go
- networking/v1alpha3/workload_entry.proto
- networking/v1beta1/destination_rule_alias.gen.go
- networking/v1beta1/service_entry_alias.gen.go
- networking/v1beta1/workload_entry_alias.gen.go
- security/v1/authorization_policy_alias.gen.go
- security/v1/peer_authentication_alias.gen.go
- security/v1/request_authentication_alias.gen.go
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.proto
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.proto
- telemetry/v1/telemetry_alias.gen.go
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.proto
Depends on https://github.com/istio/tools/pull/3050.
This PR adds support for a new cel pre-processor: https://github.com/howardjohn/celpp.
This avoids the need to write incredibly verbose and error prone boilerplate to workaround limitations in the CEL language.
----
This PR has a few commits:
* Run with no changes. The pre-processor formats the CEL expression, so this has some trivial changes
* Incrementally migrate things to the new CEL macros where it makes sense to simplify
* Add documentation for validation (includes more than just the new stuff)
> Validation: add documentation and use CEL pre-processor

- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- tests/testdata/authz-valid.yaml
This allows applying a policy like
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
name: allow-waypoint
spec:
selector:
matchLabels:
app: echo
action: ALLOW
rules:
- from:
- source:
serviceAccounts: ["waypoint"]
```
To get the semantics of "allow the waypoint in the same namespace". 
It is common in k8s to allow configurations to be written without a namespace specified and have the namespace of references implied by the namespace it is eventually written to. This allows taking the same policy and applying it to many places without the need for modification/templating. As far as I know, this is allowed with virtually every k8s core type and Istio type today.
Note this just changes docs to match the implementation in https://github.com/istio/istio/pull/54745 …
> AuthorizationPolicy serviceAccount: allow same namespace

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- releasenotes/notes/3412.yaml
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.pb.html
- type/v1beta1/selector.proto
This PR removes CEL validation from PolicyTargetRef for two primary reasons:
1. Allow vendor extensions by allowing Istio policy to target non-Istio references
2. Allow Istio policy to target a GatewayClass
> Validation: remove CEL for PolicyTargetRef to allow vendor extensions

- annotation/annotations.gen.go
- annotation/annotations.yaml
- releasenotes/notes/3361.yaml
Relates to https://github.com/istio/istio/issues/49829
This is the API side, putting it up for comment/TOC approval with a hold, impl pending.
> Add a pod-level opt-out for ambient DNS proxying, in preparation for enabling that by default globally

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/network.proto
- releasenotes/notes/mesh-network-internal-addr-config.yaml
Add comments explaining the ability to use MeshNetworks to configure Envoy's internal_address_config via
ENABLE_HCM_INTERNAL_NETWORK
https://github.com/istio/istio/issues/53402
Related: https://github.com/istio/istio/issues/52037
> Clarify relationship btw MeshNetworks and ENABLE_HCM_INTERNAL_NET

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
Follow-up of https://github.com/istio/istio/pull/55410
> Remove non-zero requirement on connectionPool.tcp.IdleTimeout

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
this's a proposal for https://github.com/istio/istio/issues/53408
With this patch, users will be able mount a secret into pilot discovery pod as env variable, then pilot will read from it and send to all proxies.
> support read header value from env variable

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- kubernetes/customresourcedefinitions.gen.yaml
Add support for envoy's [FailurePolicy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#enum-extensions-wasm-v3-failurepolicy) `FAIL_RELOAD` 
Resolves #3470
> wasm: add wasm plugin fail strategy reload

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1/destination_rule_alias.gen.go
- networking/v1/gateway_alias.gen.go
- networking/v1/service_entry_alias.gen.go
- networking/v1/sidecar_alias.gen.go
- networking/v1/virtual_service_alias.gen.go
- networking/v1/workload_entry_alias.gen.go
- networking/v1/workload_group_alias.gen.go
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
- networking/v1alpha3/workload_entry.pb.go
- networking/v1alpha3/workload_entry.proto
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.proto
- networking/v1beta1/destination_rule_alias.gen.go
- networking/v1beta1/gateway_alias.gen.go
- networking/v1beta1/service_entry_alias.gen.go
- networking/v1beta1/sidecar_alias.gen.go
- networking/v1beta1/virtual_service_alias.gen.go
- networking/v1beta1/workload_entry_alias.gen.go
- networking/v1beta1/workload_group_alias.gen.go
- releasenotes/notes/storage-version.yaml
Fixes https://github.com/istio/istio/issues/55302
> Migrate storage version of networking APIs to v1

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
Added for dual cert support but realized later that envoy supports single cert for validation. So decided to uses ca_cert in ServerTLSSettings. Hiding this for now
Ref
#3466  https://github.com/istio/istio/pull/55760
> hide ca cert from tls certificates

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Closes #3258.
Happy to take guidance on better language; it felt best as a clarifying note to me.
> update sourceLabels and sourceNamespace docs

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
As mentioned in the [deprecation notes](https://istio.io/latest/news/releases/1.25.x/announcing-1.25/change-notes/#deprecation-notices), it should be `istio.io/reroute-virtual-interfaces`
Related to: https://github.com/istio/istio/issues/57662
> Fix incorrect annotation in kubevirtInterfaces docs

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Change-Id: I6c64ddd71aee82b570c7df25f13e2d710a046558
> stats: add bootstrap annotations for stats flush and eviction

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Corrected an error in the config example.
Confirmed that the validation now passes as shown below.
Invalid when we use `from_cookies` as a field name:
```
k apply --dry-run=server -f test-jwt.yaml
Error from server (BadRequest): error when creating "test-jwt.yaml": RequestAuthentication in version "v1" cannot be handled as a RequestAuthentication: strict decoding error: unknown field "spec.jwtRules[0].from_cookies"
```
Valid when we use `fromCookies`:
```
k apply --dry-run=server -f test-jwt.yaml
requestauthentication.security.istio.io/jwt-on-ingress created (server dry run)
```
> doc: correct field name in example config
