istio/api

- mixer/v1/attributes.proto
- mixer/v1/config/descriptor/quota_descriptor.proto
- mixer/v1/quota.proto
Also includes attribute protocol definitions for 'duration'
> Update quota surface to support prefetching.

- mixer/v1/attributes.proto
- mixer/v1/check.proto
- mixer/v1/config/cfg.proto
- mixer/v1/config/descriptor/attribute_descriptor.proto
- mixer/v1/config/descriptor/label_descriptor.proto
- mixer/v1/config/descriptor/log_entry_descriptor.proto
- mixer/v1/config/descriptor/metric_descriptor.proto
- mixer/v1/config/descriptor/monitored_resource_descriptor.proto
- mixer/v1/config/descriptor/principal_descriptor.proto
- mixer/v1/config/descriptor/quota_descriptor.proto
- mixer/v1/config/descriptor/value_type.proto
- mixer/v1/quota.proto
- mixer/v1/report.proto
- mixer/v1/service.proto
While I was here, update copyright messages.
> Update QuotaResponse to include a status result.

- mixer/v1/config/descriptor/log_entry_descriptor.proto
See https://github.com/istio/api/issues/49.
> Update the LogEntryDescriptor to match Metric and Quota Descriptors

- mixer/v1/config_api_swagger.yaml
This adds mixer config API spec with foremost focus on Alpha. 
https://docs.google.com/document/d/17Ww_wS72UvGa15WipUibyLetlLNjK3hnqi-DfhkpoMg/edit#heading=h.x8zcnr9affp0
> Mixer config api swagger with a link to doc

- proxy/v1/config/cfg.proto
Field needed for https://github.com/istio/manager/pull/463
https://github.com/istio/manager/issues/67
> added egress proxy service to proxyconfig

- mixer/v1/config/cfg.proto
- mixer/v1/config/descriptor/attribute_descriptor.proto
- mixer/v1/config/descriptor/log_entry_descriptor.proto
- mixer/v1/config/descriptor/metric_descriptor.proto
- mixer/v1/config/descriptor/monitored_resource_descriptor.proto
- mixer/v1/config/descriptor/principal_descriptor.proto
- mixer/v1/config/descriptor/quota_descriptor.proto
- mixer/v1/config/descriptor/value_type.proto
- mixer/v1/service.proto
Update documentation on our API surface to line up with today's world. Various other small touchups.
> Update mixer API documentation

- proxy/v1/config/proxy_mesh.proto
Adds Zipkin address. Will be used by https://github.com/istio/manager/pull/642.
> Zipkin address

- mixer/v1/global_dictionary.yaml
I think it is better to check the global dictionary file here.
If listing them in a doc, you have to manually copy them from doc to code. 
By storing here, we will:
1) have version control, who/when the file is updated
2) can use script to convert this file to your code, better than manually copy
> Global dictionary in yaml

- mixer/v1/config/descriptor/log_entry_descriptor.proto
- mixer/v1/config/descriptor/metric_descriptor.proto
Fix some typos in the comments.
> Polish comments

- mixer/v1/check.proto
- mixer/v1/quota.proto
- mixer/v1/service.proto
This reverts commit 71b04fb00fd74514bae57e39b4945cf4f17bde5e.
> Revert "Combine Quota functionality into the Check method. (#124)"

- proxy/v1/config/egress_rule.proto
Issue https://github.com/istio/istio/issues/552.
Pilot model, including validation is here - https://github.com/vadimeisenbergibm/pilot/tree/egress_rule, to be merged after this merge.
> added egress rule message format

- mixer/v1/config/cfg.proto
- proxy/v1/config/dest_policy.proto
- proxy/v1/config/egress_rule.proto
- proxy/v1/config/http_fault.proto
- proxy/v1/config/ingress_rule.proto
- proxy/v1/config/route_rule.proto
Changes as per design: https://docs.google.com/document/d/1fGZpgFWJZhNRlQoBlCW815aOFR-ewfxKhla0CcPRsBM/edit#
Migration instructions and bookinfo sample changes tracked here: https://github.com/istio/istio/pull/558
> Unified config api

- mixer/v1/config/cfg.proto
- mixer/v1/global_dictionary.yaml
Add destination.* attribute names to the global dictionary
> Update Mixer global dictionary with destination.* attributes

- mixer/v1/config/cfg.proto
1. Update Mixer rule.selector to rule.match per design doc
2. Update comments.
> Update Mixer rule.selector to rule.match per design doc

- proxy/v1/config/quota.proto
This is just a proposal.
Please see detail design in:
https://docs.google.com/document/d/15g3iYbDwd6KHOGOq1vroo9cALXnrYxrs9Ilm7iDX1xM/edit?ts=59d12c03#
> Add quota runtime config.

- proxy/v1/config/proxy_mesh.proto
These changes are needed to pass parameters to pilot agent at startup
> API changes for securing istio components

- mixer/v1/global_dictionary.yaml
Design doc: http://goo.gl/9dokCX
> Add auth attributes.

- scripts/pre-commit
Fixes https://github.com/istio/api/issues/249
> add a pre-commit script that generates pb.go files from our protos

- mixer/v1/config/client/api_spec.proto
- mixer/v1/config/client/client_config.proto
Proto boolean default value is fault.  Change the default to be enabled.
Also fixed a typo for default api_key
> Rename enable_mixer_check to disable_check_calls.

- api_dependencies.bzl
- check_bazel_version.bzl
- protobuf.bzl
Mostly from https://github.com/istio/istio/pull/1891
> Support bazel 0.8.x

- mixer/v1/template/extensions.pb.go
- mixer/v1/template/standard_types.pb.go
- mixer/v1/template/standard_types.proto
Mark Email and Url as DO NOT USE. These types will not be publicized in the template.md file, so hopefully developers will stay away from these undeveloped features.
> Mark some types as DO NOT USE.

- mixer/v1/config/client/client_config.pb.go
- mixer/v1/config/client/client_config.proto
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Fix typo per comments by @ayj in PR#318.
> Fix typo in comments.

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
This is to address the following github issue: https://github.com/istio/istio/issues/3031
> Expose concurrency flag of envoy

- broker/dev/istio.broker.dev.pb.html
- broker/dev/service_class.pb.go
- broker/dev/service_class.proto
> add package comments for broker.

- routing/v1alpha2/external_service.pb.go
- routing/v1alpha2/external_service.proto
- routing/v1alpha2/istio.routing.v1alpha2.pb.html
resolves https://github.com/istio/istio/issues/3581
> enums are case sensitve, updating examples so users are not confused

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
wrt https://github.com/istio/istio/issues/3745
> enable custom path to proxy template file

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
@frankbu the documentation for gateway selectors was incorrect. See here https://github.com/istio/api/issues/377
> Gateway selector doc

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
- clarify short name resolution
- remove faults (for now)
> Update networking APIs

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
> Fix a typo

- Makefile
- networking/v1alpha3/virtual_service.pb.go
Bad import / no build in CI...
> Patch for networking gogo import

- STYLE-GUIDE.md
avoid using config.istio.io because it's being deprecated.
> Update CRD example

- mixer/v1/global_dictionary.yaml
This PR adds the new attributes proposed in [Updated Source & Destination Attributes](https://docs.google.com/document/d/1IcR6C7j5Vl-4Jx8ervVT4lCTBDrBgsD7Uac77K5C5h4/edit#) to the
global dictionary used for communication with Mixer.
> Update global dictionary with new attributes

- mixer/v1/global_dictionary.yaml
> attributes: rename grpc attributes to use underscore

- Makefile
- networking/v1alpha3/envoy_filter.pb.go
Added a golang => gogo mapping for the struct as well. This helps with the generation of the struct related code.
> Fix envoy_filter Struct generation issue.

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Actually redirect response code is HTTP 301.
> Fix HTTPRedirect doc.

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Spec was missing gateway describe in the text.
> Fix TLS example

- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
> Update RBAC comments for Istio 1.0.

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
See
* https://github.com/istio/istio/pull/7109 
* https://github.com/istio/istio.github.io/pull/1817
> doc updates

- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
align with istio/istio#6874
/cc @ymesika
> update rbac api version to rbac.istio.io/v1alpha1.

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.proto
So it can be published in istio.io.
>  Add $location marker for authentication policy proto

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
> Fix envoyfilter doc on multiple configs for a workload

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Error pointed out here: https://github.com/istio/istio.github.io/pull/1961
> Small DestinationWeight doc fix

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
> assorted doc nits

- mesh/v1alpha1/config.proto
- mixer/adapter/model/v1beta1/infrastructure_backend.proto
- mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
- mixer/v1/config/client/client_config.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.proto
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.proto
This is to satisfy linting requirements from istio.github.io.
> Add periods at the end of description strings.

- mixer/v1/config/client/api_spec.pb.go
- mixer/v1/config/client/api_spec.proto
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Minor update to reflect the current message structure.
> Fix HTTPAPISpec doc.

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
Issue: https://github.com/istio/api/issues/610
> Change TargetSelector documentation to be 'workload oriented'

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
Signed-off-by: Venil Noronha <veniln@vmware.com>
/cc @rshriram
> Update weighted cluster support docs in TCP/TLS

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
target -> targets
Supersedes bad pr https://github.com/istio/istio.io/pull/2946
> Fix typo, 'target' is not known 

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.proto
(cherry picked from commit 001174fb4d0ff37e5c585a72727b7623ae65a30d)
> Comment fixes.

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- proto.lock
- python/istio_api/networking/v1alpha3/gateway_pb2.py
Sorry merged by accident. Didn't see @costinm 's hold
Reverts istio/api#778
> Revert "Enabling SDS in the gateway"

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
Changing "gateway" to "gateways". Without this change, the yaml doesn't get applied successfully.
> change gateway to gateways

- networking/v1alpha3/istio.networking.v1alpha3.pb.html
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
I think this is correct, but what do you think?
> VirtualService configuration

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
Fixes for https://github.com/istio/api/issues/853 , https://github.com/istio/api/issues/852 , https://github.com/istio/api/issues/851 , and https://github.com/istio/api/issues/850
> Example CRD instances must be valid

- mixer/v1/config/client/client_config.proto
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
fixes https://github.com/istio/istio.io/issues/2851
> add mixerclient config to istio.io reference docs

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
> Add recommendation for gateway selector

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.pb.go
- authentication/v1alpha1/policy.proto
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
Resolves https://github.com/istio/istio.io/issues/3686
> Be precise about 'workload' vs 'workload instance'

- OWNERS
currently owner of the networking/v1alpha3 implementation in istio/istio so I would like to have some ownership of the istio/api side as well
> add Greg Hanson as reviewer/approver to istio/api repo

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Signed-off-by: Shakti <shaktiprakash.das@salesforce.com>
API doc changes for Istio issue https://github.com/istio/istio/issues/13201
> Sidecar Capture mode NONE to use Bind API changes

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Fixes https://github.com/istio/istio/issues/11203
> Clarify doc for VirtualService gateways field

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
the default was changed in the code by https://github.com/istio/istio/pull/10566
> update the default of maxRetries in DestinationRule to 1024

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
update host desc that more than one vs share same host to permit the ingress style gateway, that is two service share the same domain name and delegated by path.
#870 #873
istio/istio#12590
> update host desc that more than one vs share same host

- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
This is for the reference page on istio.io 
Related PR: https://github.com/istio/istio.io/pull/4262
> Refine RBAC API usage for TCP and gRPC services. 

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Changed proto file and re-create docs
> typo: fix typo in sidecar docs

- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
Fix some invalid commments
/assign @frankbu
> Fix invalid ServiceEntry docs (cherry-pick #932)

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Fixes https://github.com/istio/istio.io/issues/2640
> Header manipulation example 

- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
cherry-pick of https://github.com/istio/api/pull/903
> cherry-pick warning from release-1.1

- annotation/annotations.gen.go
- annotation/annotations.yaml
Also adding a few stragglers used in istio/istio and istio/installer
> Hiding alpha-level annotations.

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
The example in envoyfilter api is not right.
> fix EnvoyFilter docs

- networking/v1alpha3/sidecar.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Fixes https://github.com/istio/istio/issues/15654
Signed-off-by: Maximilian Bischoff <maximilian.bischoff@inovex.de>
> Clarify global IstioEgressListener-hosts setting docs

- networking/v1alpha3/sidecar.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
Signed-off-by: Shriram Rajagopalan <rshriram@tetrate.io>
> Sidecar doc updates

- Makefile
- Makefile.core.mk
- authentication/v1alpha1/istio.authentication.v1alpha1.json
- mcp/v1alpha1/istio.mcp.v1alpha1.json
- mesh/v1alpha1/istio.mesh.v1alpha1.json
- mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.json
- mixer/v1/config/client/istio.mixer.v1.config.client.json
- mixer/v1/istio.mixer.v1.json
- networking/v1alpha3/destination_rule.json
- networking/v1alpha3/envoy_filter.json
- networking/v1alpha3/gateway.json
- networking/v1alpha3/service_entry.json
- networking/v1alpha3/sidecar.json
- networking/v1alpha3/virtual_service.json
- policy/v1beta1/istio.policy.v1beta1.json
- rbac/v1alpha1/istio.rbac.v1alpha1.json
The changes to the json schema is due to the recent change in cue where it generates the structural schema. (It is just different format but expresses the same schema)
> Use the merged build tool image

- networking/v1alpha3/gateway.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
> Update sidecar and gateway hosts doc

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Fix word spelling error of mesh config proto
> Typo fix for mesh config proto

- networking/v1alpha3/virtual_service.proto
Fixes a non-closed quote.
Opened in favor of https://github.com/istio/istio.io/pull/5034
> Fix missing right quote

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
https://github.com/istio/istio/issues/17276
> Add an annotation option to opt-in autopilot.

- rbac/v1alpha1/istio.rbac.v1alpha1.json
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.pb.go
- rbac/v1alpha1/rbac.proto
Fixes https://github.com/istio/istio.io/issues/5127
> Fixed a few comment typos.

- networking/v1alpha3/destination_rule.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Fixes https://github.com/istio/istio.io/issues/5013
> Clarify connection pool example

- networking/v1alpha3/destination_rule.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
This was changed in https://github.com/envoyproxy/envoy/pull/8629
> Fix default doc for idle timeout

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
for https://github.com/istio/istio/issues/18621
> Add operator annotations

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
This updates ConnectionPoolSettings comments according to https://github.com/istio/istio/pull/17346
> Disable circuit breaking by default

- authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
- authentication/v1alpha1/policy.proto
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
- rbac/v1alpha1/rbac.proto
- security/v1beta1/authorization.proto
- security/v1beta1/istio.security.v1beta1.pb.html
> Manual cherry-pick #1165

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
> Fix documentation for RequestAuthentication

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Fixes https://github.com/istio/istio.io/issues/5867
> Clarify location of timeout field

- CODEOWNERS
Discussed with @geeknoid on why our 2 approvers aren't working today.   @geeknoid suggested trying individual owners
> update to individual owners - attempt to fix 2 approvers issue

- security/v1beta1/authorization.pb.go
- security/v1beta1/authorization.pb.html
- security/v1beta1/authorization.proto
- security/v1beta1/authorization_deepcopy.gen.go
- security/v1beta1/authorization_json.gen.go
Fix for https://github.com/istio/api/issues/1183
> Fix deny all authorization policy examples

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
Fixes https://github.com/istio/istio/issues/17105
> Put back doc for gateways field in http match

- kubernetes/customresourcedefinitions.gen.yaml
- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
resolves errors in https://github.com/istio/istio/pull/19762
> Change mixer CRDs to lower case

- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
This is the API annotation change to fix https://github.com/istio/istio/issues/19638
> Add kubeType annotation for mixer CRD client registration

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
See https://github.com/istio/istio/issues/19932
> Add annotation for enableCoreDump

- security/v1beta1/authorization.gen.json
- security/v1beta1/authorization.pb.go
- security/v1beta1/authorization.pb.html
- security/v1beta1/authorization.proto
- type/v1beta1/istio.type.v1beta1.pb.html
- type/v1beta1/selector.proto
For https://github.com/istio/istio/issues/19994
cc @xeviknal @howardjohn
> Fix link errors in authorization policy

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
related to Issue https://github.com/istio/istio/issues/20365
> clarify acceptable values for protocolDetectionTimeout

- operator/fixup_structs/main.go
- operator/v1alpha1/component.pb.go
- operator/v1alpha1/kubernetes.pb.go
- operator/v1alpha1/operator.pb.go
More context: https://github.com/istio/api/pull/1237#issue-365133001
> fix operator go struct tag

- operator/v1alpha1/component.pb.go
- operator/v1alpha1/component.proto
- operator/v1alpha1/istio.operator.v1alpha1.pb.html
This fixes https://github.com/istio/istio.io/issues/6498
> Make external links in Global Mesh Options page clickable

- operator/fixup_structs/main.go
- operator/v1alpha1/component.pb.go
- operator/v1alpha1/operator.pb.go
cherrypick: https://github.com/istio/api/pull/1277
> fix operator go struct tag.

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Doc updates for https://github.com/istio/istio/pull/21304
> update docs for stats patterns

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.proto
- Add `ra` for RequestAuthentication short name
- Add `pa` for PeerAuthentication short name
> Add short name for RequestAuthentication and PeerAuthentication

- Makefile.core.mk
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/proxy.pb.go
Manual cherry pick of https://github.com/istio/api/pull/1320.
> [1.5] Fix MeshConfig field tags for JSON unmarshal (#1320)

- authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
- authentication/v1alpha1/policy.proto
- kubernetes/customresourcedefinitions.gen.yaml
- mixer/v1/config/client/api_spec.proto
- mixer/v1/config/client/istio.mixer.v1.config.client.gen.json
- mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
- mixer/v1/config/client/quota.proto
- mixer/v1/istio.mixer.v1.gen.json
- mixer/v1/mixer.pb.go
- mixer/v1/mixer.proto
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.proto
To fix https://github.com/istio/istio.io/issues/6749
> Update ECMAscript to RE2

- CODEOWNERS
> Add Josh to master code owner list

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Part of https://github.com/istio/istio/pull/22395 and to fix https://github.com/istio/istio/issues/16126
> Document new sidecar annotations for setting resource limits

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
extra space causes yaml to be invalid
> delete redundant space on envoy_filter.proto

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Fix CRD error caused by https://github.com/istio/api/pull/1387
> Fix destination rule crd

- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/service_entry_deepcopy.gen.go
- networking/v1alpha3/service_entry_json.gen.go
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
- networking/v1beta1/service_entry_deepcopy.gen.go
- networking/v1beta1/service_entry_json.gen.go
Resolves https://github.com/istio/istio/issues/22971
> ServiceEntry DNS resolution sample not valid

- dictionaries/custom.txt
- istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
per https://github.com/istio/istio.io/pull/7123
Fixes https://github.com/istio/istio/issues/23345
> Change LightStep to Lightstep as it was rebranded.

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
This is already implemented in istio/istio. No problem changing the
syntax if people have concerns as it has not yet shipped - just need to make sure it makes it
into 1.6.
> Add proxy config annotation

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
- proto.lock
This isn't used anymore, that's why getting rid of this
> Remove legacy ISTIO_META_USER_SDS from documentation

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Moved as suggested in https://github.com/istio/istio.io/pull/7555.
> fixed minor typos in security/request_authentication documentation

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
To fix https://github.com/istio/istio.io/issues/7026
Keeping it consistent with  [ingressgateway](https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L9) name.
> Update gateway selector to be consistent with other names

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
> fix gateways typo

- annotation/annotations.gen.go
- kubernetes/customresourcedefinitions.gen.yaml
- policy/v1beta1/cfg.pb.go
- policy/v1beta1/cfg.proto
This is intended to fix mixer tests in https://github.com/istio/istio/pull/25263
These APIs will be removed after 1.7.
> Add x-kubernetes-preserve-unknown-fields to instances and handlers

- annotation/annotations.gen.go
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Based on the https://github.com/istio/api/pull/1493#discussion_r447717857, the `ControlPlaneAuthPolicy` applied to Envoy > Istiod.
> Update auth policy enum for proxy config

- security/v1beta1/authorization.pb.html
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/request_authentication.pb.html
- type/v1beta1/selector.proto
Manual cherry-pick of https://github.com/istio/api/pull/1550
> Fix broken link for WorkloadSelector 1.7

- security/v1beta1/authorization.pb.html
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/request_authentication.pb.html
- type/v1beta1/istio.type.v1beta1.pb.html
- type/v1beta1/selector.proto
Manual cherry-pick of https://github.com/istio/api/pull/1550
> Fix broken link for WorkloadSelector 1.6

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
Fixes  https://github.com/istio/istio/issues/22030
> Tweak locality lb docs a bit

- networking/v1alpha3/envoy_filter.gen.json
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
Update Envoy Filter docs to use the canonical names and v3 types
Refer https://github.com/istio/istio/pull/25966
> update envoy filter docs

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
related to https://github.com/istio/istio.io/pull/7983
cc @frankbu
> clarify HTTP requests timeout default

- security/v1beta1/authorization.pb.go
- security/v1beta1/authorization.pb.html
- security/v1beta1/authorization.proto
- security/v1beta1/authorization_deepcopy.gen.go
- security/v1beta1/authorization_json.gen.go
From https://github.com/istio/istio.io/pull/8061#discussion_r481469376
> Remove Telemetry v2 on Stackdriver

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
fixes: #1608
with manual cherry pick
> [release-1.7] cherry pick 1606

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
To fix https://github.com/istio/istio.io/issues/8167
Related:
https://github.com/istio/api/pull/1642
https://github.com/istio/api/pull/1610
> Fix capitalisation for accessLogEncoding

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
To fix https://github.com/istio/api/issues/1643
Found during https://github.com/istio/api/pull/1641
Related:
https://github.com/istio/api/pull/1610
> Fix inconsistent rendering of enum constant and code examples

- security/v1beta1/authorization.pb.go
- security/v1beta1/authorization.pb.html
- security/v1beta1/authorization.proto
- security/v1beta1/authorization_deepcopy.gen.go
- security/v1beta1/authorization_json.gen.go
Cherrypick of this to release 1.7 will be the fix for https://github.com/istio/istio.io/issues/8178
> Fix section end

- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec
> Fix link and bullet point rendering for IstioOperatorSpec

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
> [release-1.7] cherry pick #1648 clarify http retry attempts 

- analysis/v1alpha1/message_json.gen.go
- authentication/v1alpha1/policy_json.gen.go
- meta/v1alpha1/status_json.gen.go
- networking/v1alpha3/destination_rule_json.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
- networking/v1alpha3/gateway_json.gen.go
- networking/v1alpha3/service_entry_json.gen.go
- networking/v1alpha3/sidecar_json.gen.go
- networking/v1alpha3/virtual_service_json.gen.go
- networking/v1alpha3/workload_entry_json.gen.go
- networking/v1alpha3/workload_group_json.gen.go
- networking/v1beta1/destination_rule_json.gen.go
- networking/v1beta1/gateway_json.gen.go
- networking/v1beta1/service_entry_json.gen.go
- networking/v1beta1/sidecar_json.gen.go
- networking/v1beta1/virtual_service_json.gen.go
- networking/v1beta1/workload_entry_json.gen.go
- security/v1alpha1/ca_json.gen.go
- security/v1beta1/authorization_policy_json.gen.go
- security/v1beta1/jwt_json.gen.go
- security/v1beta1/peer_authentication_json.gen.go
- security/v1beta1/request_authentication_json.gen.go
- type/v1beta1/selector_json.gen.go
I am not sure why this wasn't done automatically, might be a bug in our
auto update logic
> Regenerate json code

- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
Attempt to fix https://github.com/istio/istio/issues/24739
Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec
> Add example for how to use IstioOperatorSpec

- label/label.go
From approved RFC: https://docs.google.com/document/d/1ciVTulP-ClrJUcVKBKrbK_WHVjCfCXlymzjKP3sQW3A/edit#heading=h.xw1gqgyqs5b
> Add cluster label.

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Ran `make clean gen` and `make proto-commit`.
> Add missing quote in AuthenticationPolicy example.

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.proto
Result:
```
$ ki get pa
NAME      MODE      AGE
default   DISABLE   14h
```
> Add MODE column to PeerAuthentication

- releasenotes/README.md
This adds the skeleton for release notes to API. Further pull requests coming to: 
* add a check to make sure release notes are present or acknowledged similar to the test in istio/istio
* allow generation of release notes based on multiple repositories
> Add release notes

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/workload_group.gen.json
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.pb.html
- networking/v1alpha3/workload_group.proto
Ref: https://preliminary.istio.io/latest/docs/reference/config/networking/workload-group/#ReadinessProbe
> Fix workload-group docs

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
* clarify index support for HTTP_ROUTE
* improve wording
Fixes https://github.com/istio/api/issues/1747
> clarify INSERT support for HTTP_ROUTE (#1625)

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
Update the comment to match the latest implementation.
cc @howardjohn @louiscryan
> update ext-authz API comment

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- security/v1beta1/authorization_policy.gen.json
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Fix additional comments from @louiscryan in https://github.com/istio/api/pull/1757 and also properly hide the `provider` field.
> update ext-authz comment

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- security/v1beta1/authorization_policy.gen.json
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Fix https://github.com/istio/api/issues/1778, manual cherrypick https://github.com/istio/api/pull/1759
> [release-1.8] update ext-authz comment

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig
> Fix rendering for proxyMetadata

- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
From post-merge comments on https://github.com/istio/api/pull/1804
> Updating description for canonical service labels.

- analysis/v1alpha1/message.pb.go
- authentication/v1alpha1/policy.pb.go
- mcp/v1alpha1/mcp.pb.go
- mcp/v1alpha1/metadata.pb.go
- mcp/v1alpha1/resource.pb.go
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/proxy.pb.go
- meta/v1alpha1/status.pb.go
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/workload_entry.pb.go
- networking/v1alpha3/workload_group.pb.go
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/workload_entry.pb.go
- proto.lock
- security/v1alpha1/ca.pb.go
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/jwt.pb.go
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/request_authentication.pb.go
- type/v1beta1/selector.pb.go
The latest build image uses gogo/protobuf 1.3.2. 
Only did the following.
1. make clean gen
2. make proto-commit
> Generate protos

- common/Makefile.common.mk
see https://github.com/istio/istio/issues/29490
> Update common/Makefile.common.mk to use release-1.9

- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Fix https://github.com/istio/istio/issues/29747
> fix request authentication comment

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.proto
Fix of api for https://github.com/istio/istio/issues/30312
> Add CRD labels to WorkloadGroup

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
> ext-authz: unhide the CUSTOM action for 1.9

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
This PR fix the issue #30611 on istio/istio
https://github.com/istio/istio/issues/30611
> [#30611] Fix perTryTimeout documentation to reflect the code

- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/gateway_deepcopy.gen.go
- networking/v1beta1/gateway_json.gen.go
- releasenotes/notes/1878.yaml
fix yaml in gateway reference doc
https://github.com/istio/istio.io/pull/8923/files
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>
> fix yaml in gateway reference doc

- feature/stability.proto
- stability/level.proto
This is based on current discussions and design from https://docs.google.com/document/d/1ZcTIdHYNnLpwgLJa8tWg0YwsyHAmc_4lXguLmMQvAj0/edit?resourcekey=0-6OWzJ5cnlh_oYl4gFMbOuA#heading=h.lrto46ego5qb
Comments are warmly welcome!
/cc @nmittler @therealmitchconnors @douglas-reid @brian-avery
> Define Istio Stability Levels

- go.mod
- go.sum
Fixes https://github.com/istio/api/issues/1859
> Update dependencies to mirror istio/istio

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
Self explanatory. Minor  grammar fixes.
> Minor grammar fix

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
To fix https://github.com/istio/istio/issues/31325
> Fix broken link for AuthorizationPolicy

- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
Attempt to fix https://github.com/istio/istio/issues/30897
> Add more info if custom ns is used to install Istio

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
Indentation and blank lines corrected so that the html renders better
> Adjust VirtualService documentation format

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- releasenotes/notes/31248.yaml
For https://github.com/istio/istio/issues/31248
> Add sidecar.istio.io/agentLogLevel annotation

- operator/v1alpha1/common.go
- operator/v1alpha1/common_test.go
For: https://github.com/istio/api/issues/1938
> Fix BoolValueForPB.GetValue allow nil

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
I did a quick grep, sems these are the only cases of this.
> Fix extra space in DR example

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/network.proto
for https://github.com/istio/istio/issues/31862
> fix meshnetworks example

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
> Document how to configure proxy config

- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
> docs: clear sourceLabels

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Fixes https://github.com/istio/api/issues/2033
> fix the html issue of unescaped < character

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
> release-1.9: fix the html issue of unescaped < character

- security/v1beta1/jwt.pb.go
- security/v1beta1/jwt.pb.html
- security/v1beta1/jwt.proto
To fix https://github.com/istio/istio.io/issues/9914
> Fix jwt rule note

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
To fix https://github.com/istio/istio/issues/32598
> Use RE2 instead of ECMAscript regex-based match

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Part of https://github.com/istio/istio.io/issues/10116
Signed-off-by: su225 <suchithjn22@gmail.com>
> fix `credential_name` documentation

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Fixes https://github.com/istio/api/issues/2015
Fixes https://github.com/istio/community/issues/624
> Update envoy TLS configuration link

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>
> update docs for source ip support with tcp

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- networking/v1alpha3/envoy_filter_deepcopy.gen.go
- networking/v1alpha3/envoy_filter_json.gen.go
Fixes istio/istio#32415
This example doesn't actually work (see referenced issue). I copied the correct example from the docs: https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/
> Fix config_source in EnvoyFilter docstring

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
Since it is no longer needed:  https://github.com/istio/istio/pull/33129
> remove the doc for configuring sni-dnat

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
ref: https://github.com/istio/istio/pull/35721
> move annotation to istio/api

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1beta1/authorization_policy.gen.json
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- security/v1beta1/authorization_policy_deepcopy.gen.go
- security/v1beta1/authorization_policy_json.gen.go
- security/v1beta1/request_authentication.gen.json
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Update to clarify details of fields in authz and JWT:
- Update the CUSTOM action is now in alpha stage
- Clarify the `host`, `path`, `principal`, `requestPrincipal` and a few more fields in authz
- Updated a few example configs
@myidpt @liminw PTAL, thanks.
> update authz and JWT documentation

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
ref: https://github.com/istio/istio/pull/36592
> move port label to api repo

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
For https://github.com/istio/istio/issues/36069
According to api guide https://github.com/istio/api/blob/master/GUIDELINES.md `Loosening validation is permitted`
> Loosen weight validation

- releasenotes/notes/fix-telemetry-doc.yaml
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
- telemetry/v1alpha1/telemetry_deepcopy.gen.go
- telemetry/v1alpha1/telemetry_json.gen.go
This PR try to improve [Telemetry API](https://preliminary.istio.io/latest/docs/reference/config/telemetry/#AccessLogging-Filter) doc, I'm not sure this is the right way, feel free to close this if not.
> fix telemetry doc

- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1alpha3/service_entry_deepcopy.gen.go
- networking/v1alpha3/service_entry_json.gen.go
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/service_entry.proto
- networking/v1beta1/service_entry_deepcopy.gen.go
- networking/v1beta1/service_entry_json.gen.go
ref: https://github.com/istio/istio.io/pull/10722
> fix httpbin.com -> example.com

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/virtual_service.gen.json
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.gen.json
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
> fix retryOn doc

- security/v1beta1/jwt.pb.go
- security/v1beta1/jwt.pb.html
- security/v1beta1/jwt.proto
- security/v1beta1/request_authentication.gen.json
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
Clarify the handling of multiple tokens and be consistent with the https://istio.io/latest/docs/concepts/security/#request-authentication
> clarify multiple tokens case for request authentication API

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
`IstioGatewayPortLabel` should be in the label package
I will update istio if merge
> Update the package where the variable resides

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Document the behaviour introduced as part of https://github.com/istio/istio/pull/38604
RFC: [auto-sni-aupport](https://docs.google.com/document/d/1pTUl-Ng3nXAWJb7UGJtalftznpxQEfID/)
> Document auto_sni behaviour

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
ref: https://github.com/istio/istio/pull/38167
> move node selector annotation to api repo

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- releasenotes/notes/2374.yaml
Regarding the added feature istio/istio#34832
> Document new sidecar annotation to exclude interfaces 

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
This PR fixes a typo in EnvoyFilter documentation.
> Fix typo fiter -> filter in EnvoyFilter documentation

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Clarify that EnvoyFileAccessLogProvider labels == JSON
Cherry pick of #2401 to 1.14 branch
> [1.14 cherry pick] Clarify that EnvoyFileAccessLogProvider labels == JSON 

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
Missed this just before merging
> Fix direct response doc

- extensions/v1alpha1/wasm.pb.go
- extensions/v1alpha1/wasm.pb.html
- extensions/v1alpha1/wasm.proto
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- scripts/validate.sh
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.pb.html
- security/v1beta1/request_authentication.proto
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
Run `scripts/validate.sh` until it passes. Does need https://github.com/istio/istio/pull/39881 to do this.
Note: it would be great to run this in CI but we have a circular dependency on istio/istio to run `istioctl validate` unfortunately.
> Validate and fix all samples

- authentication/v1alpha1/policy.pb.go
- envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
- extensions/v1alpha1/wasm.pb.go
- mcp/v1alpha1/mcp.pb.go
- mcp/v1alpha1/metadata.pb.go
- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/network.pb.go
- mesh/v1alpha1/proxy.pb.go
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/workload_group.pb.go
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/service_entry.pb.go
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/workload_group.pb.go
- operator/v1alpha1/operator.pb.go
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/jwt.pb.go
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/request_authentication.pb.go
- telemetry/v1alpha1/telemetry.pb.go
Running make gen for some other API change which I am working on, resulted in many additional
changes showing up in my local repo. So pushing a separate review for the same to check if this is relevant.
> Running make gen

- networking/v1alpha3/sidecar.gen.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.gen.json
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
should be merged along with https://github.com/istio/istio/pull/40265
Issue: https://github.com/istio/istio/issues/40245
> sidecar defaultEndPoints should be IPv6 compatible

- networking/v1alpha3/sidecar.gen.json
- networking/v1alpha3/sidecar.pb.go
- networking/v1alpha3/sidecar.pb.html
- networking/v1alpha3/sidecar.proto
- networking/v1beta1/sidecar.gen.json
- networking/v1beta1/sidecar.pb.go
- networking/v1beta1/sidecar.proto
@howardjohn had some [review comments](https://github.com/istio/api/pull/2447#discussion_r938901828) on the previous PR which were not addressed.
> enhance sidecar IstioIngressListener defaultEndPoint description

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Aligns with https://github.com/istio/istio.io/pull/11369
> Hide dns certificate management from docs

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- label/labels.gen.go
- label/labels.pb.html
- label/labels.yaml
Lable is to replace annotation
> Added `sidecar.istio.io/inject` label

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
> Update tls des

- proto.lock
Looks like some previous PR forgot to run proto-commit
> Run proto-commit

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
- releasenotes/notes/delegate-vs-regex.yaml
Resolves #2527 
Signed-off-by: luohua13 <jcwang@alauda.io>
> remove comment about not support regex for delegete vs

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
I have helped on >10 issues from these confusion, so hoping to clear things up.
> consistent hash: add warnings

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
> Fix a tiny typo in virtualservice documentation

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.pb.html
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.gen.json
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
> Correct confusing typo in the authz policy proto

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>
> clarify warmup duration docs in destination rule

- operator/v1alpha1/operator_json.go
fixes: https://github.com/istio/api/pull/2633
> fix depguard

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
> Clarify protocol description for Gateway port

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service.pb.go
- networking/v1beta1/virtual_service.proto
Fix issue https://github.com/istio/istio/issues/43710.
The pr https://github.com/istio/istio/pull/43736 has been merged.
> Update api comment about query parameter.

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Fixes https://github.com/istio/istio/issues/42075
> Updated documented default refresh rate

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
Documented as per https://github.com/istio/istio/blob/master/pkg/config/security/security.go#L190
Fixes https://github.com/istio/istio/issues/43212
> Document available cipher list for ServerTLSSettings

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
For more details, please look at this PR: https://github.com/istio/istio/pull/44161.
> Add annotation istio.io/rev

- proto.lock
Requires https://github.com/istio/common-files/pull/824/files
> Update protc-gen-gateway; make gen

- mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
docs changes for https://github.com/istio/istio/pull/45104
> docs changes for crl support

- networking/v1alpha3/gateway.gen.json
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1alpha3/sidecar.gen.json
- networking/v1beta1/gateway.gen.json
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
- networking/v1beta1/sidecar.gen.json
Docs changes for https://github.com/istio/istio/pull/43209/files
> docs changes for ocsp staple support

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
fix error introduced by https://github.com/istio/api/pull/2514
> envoyfilter: fix wrong doc

- networking/v1alpha3/destination_rule.gen.json
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.gen.json
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
- releasenotes/notes/destination-rule-default-values.yaml
> Wrong defaults for Destination Rule

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Fixes https://github.com/istio/api/issues/2892
> Fix AuthorizationPolicy typo

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
Related to https://github.com/istio/istio.io/pull/13753
> Fix typo Authorizaion  to Authorization

- kubernetes/customresourcedefinitions.gen.yaml
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- meta/v1alpha1/status.pb.html
- operator/v1alpha1/istio.operator.v1alpha1.pb.html
With the new build-tools image, `make gen` will yield differences, so putting them into a single PR.
> Run 'make gen' with new build-tools image

- kubernetes/customresourcedefinitions.gen.yaml
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.proto
Apparently it needs to be line 1.
> Properly hideFromDocs targetRef

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
Fixing an incorrect comment on the SIDECAR_INBOUND line.
> fix an incorrect statement

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
correctly in the docs.
Adopted from https://github.com/istio/istio.io/pull/10942.
> GRPC-WEB is a valid port protocol, but not listed

- envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
- envoy/extensions/stackdriver/config/v1alpha1/config.proto
- telemetry/v1alpha1/telemetry.pb.go
- telemetry/v1alpha1/telemetry.pb.html
- telemetry/v1alpha1/telemetry.proto
Part of [#47533](https://github.com/istio/istio/issues/47533)
> Update CEL documentation to capture type checking errors.

- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- networking/v1beta1/gateway.pb.go
- networking/v1beta1/gateway.proto
https://istio.slack.com/archives/C3TEGNZ7W/p1695876172041579
https://github.com/istio/istio/blob/c9b1d29e5a1ac5a7a193c999627a56308eedc858/security/pkg/pki/ca/ca.go#L55-L58
I believe this is what it's supposed to say.
> update expected filenames for tls terminating key/secret

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
- operator/v1alpha1/istio.operator.v1alpha1.pb.html
- operator/v1alpha1/operator.pb.go
- operator/v1alpha1/operator.proto
Fix links and code snippets to render properly.
> docs: fix rendering of links and code snippets

- networking/v1alpha3/envoy_filter.pb.go
- networking/v1alpha3/envoy_filter.pb.html
- networking/v1alpha3/envoy_filter.proto
- releasenotes/notes/bds-removal.yaml
See https://github.com/istio/istio/pull/48693.
Change-Id: I82b18264d957a5702205aedf131c9c4246ab6634
> agent: remove BDS

- annotation/annotations.pb.html
- label/labels.pb.html
follow up: https://github.com/istio/common-files/pull/968/files
xref: https://github.com/istio/istio.io/issues/14453
> update annotations and labels page

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
- networking/v1beta1/destination_rule.pb.go
- networking/v1beta1/destination_rule.proto
Unhides docs for max_concurrent_streams. 
https://github.com/istio/istio/pull/48615
> Add docs for max_concurrent_streams

- kubernetes/customresourcedefinitions.gen.yaml
- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.proto
```
$ kag authorizationpolicies.security.istio.io
NAMESPACE   NAME      ACTION   AGE
foo         httpbin   ALLOW    11m
```
Just a nice helper
> authz: add column for actions

- kubernetes/customresourcedefinitions.gen.yaml
Generate with https://github.com/istio/tools/pull/2854
> Document all CRD enum options in CRD description

- security/v1/peer_authentication.pb.go
- security/v1/peer_authentication.proto
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
> Update PeerAuth Documentation to indicate that API Dev is frozen

- go.mod
https://github.com/istio/istio/issues/48443
> Update go to 1.22

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Please see @alam0rt's PR #2047 (with @howardjohn's approval) - it sat unloved and eventually expired, but it's a trivial change, and worthwhile to resurrect. I've recreated it here with a modern `make gen`.
> Update docs on draining (from #2047)

- security/v1/authorization_policy.pb.go
- security/v1/authorization_policy.proto
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.pb.html
- security/v1beta1/authorization_policy.proto
Stackdriver is removed from OSS.
> update authz comment

- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
Fixes https://github.com/istio/api/issues/1783
> proxy config: clarify concurrency docs

- networking/v1/destination_rule_alias.gen.go
- networking/v1/gateway_alias.gen.go
- networking/v1/service_entry_alias.gen.go
- networking/v1/sidecar_alias.gen.go
- networking/v1/virtual_service_alias.gen.go
- networking/v1/workload_entry_alias.gen.go
- networking/v1/workload_group_alias.gen.go
- networking/v1beta1/destination_rule_alias.gen.go
- networking/v1beta1/gateway_alias.gen.go
- networking/v1beta1/service_entry_alias.gen.go
- networking/v1beta1/sidecar_alias.gen.go
- networking/v1beta1/virtual_service_alias.gen.go
- networking/v1beta1/workload_entry_alias.gen.go
- networking/v1beta1/workload_group_alias.gen.go
- security/v1/authorization_policy_alias.gen.go
- security/v1/peer_authentication_alias.gen.go
- security/v1/request_authentication_alias.gen.go
- telemetry/v1/telemetry_alias.gen.go
This adds comments to the aliases
> Regen API with new tools

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1/virtual_service_alias.gen.go
- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
- networking/v1beta1/virtual_service_alias.gen.go
Finishing off https://github.com/istio/api/pull/3228
cc @eabykov
> fix re2 link

- security/v1/peer_authentication.pb.go
- security/v1/peer_authentication.proto
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.pb.html
- security/v1beta1/peer_authentication.proto
manual cherry-pick of #3184, updates PeerAuthentication docs.
> manual cherry-pick of #3184

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
Test will fail until https://github.com/istio/tools/pull/2983 is merged
> Make TTL allow duration=0s again

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
add new pattern SERVICE_NAME variable for stat prefix
> add new pattern SERVICE_NAME variable for stat prefix

- kubernetes/customresourcedefinitions.gen.yaml
- type/v1beta1/selector.pb.go
- type/v1beta1/selector.proto
This adds the ability to use SE as a targetRef in policies. We already have Service, so its natural to work with SE.
Implementation is in https://github.com/istio/istio/pull/52154
> Allow targetRef to SE

- kubernetes/customresourcedefinitions.gen.yaml
> Regen after intorstr changes

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/workload_group.pb.go
- networking/v1alpha3/workload_group.proto
Master PR https://github.com/istio/api/pull/3295
Fixes https://github.com/istio/istio/issues/52749
> 1.23: fix workload group regression

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1/service_entry_alias.gen.go
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.proto
- networking/v1beta1/service_entry_alias.gen.go
- tests/testdata/serviceentry-valid.yaml
Adds regression test and fixes the issue
> Fix over-correcting new SE CEL validation

- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.pb.html
- networking/v1alpha3/destination_rule.proto
As per https://github.com/istio/istio/blob/master/pkg/config/validation/agent/validation.go#L301
> Clarify filemounted crl usage

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
These have no usage within Istio at all anymore.
> annotations: remove obsolete entries

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
- releasenotes/notes/native-sidecar-annotation.yaml
As part of https://github.com/istio/istio/issues/53452, this PR generates the annotation docs.
> annotations: create an annotation for native sidecars

- annotation/annotations.gen.go
- annotation/annotations.yaml
Added in istio in https://github.com/istio/istio/pull/53476
> Add ingress bypass annotation to the API

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Support for annotation removed in
https://github.com/istio/istio/pull/53437
> Remove enableCoreDump annotation

- networking/v1/service_entry_alias.gen.go
- networking/v1alpha3/service_entry.pb.go
- networking/v1alpha3/service_entry.pb.html
- networking/v1alpha3/service_entry.proto
- networking/v1beta1/service_entry_alias.gen.go
There is no 'egress policy'.
Fixes https://github.com/istio/istio/issues/53904
> Fix incorrect SE docs

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
- mesh/v1alpha1/proxy.pb.go
- mesh/v1alpha1/proxy.proto
hide `lightstep`, `stackdriver` and `opencensus` from doc
xref: https://github.com/istio/api/pull/3367
> hide tracer provider

- mesh/v1alpha1/config.pb.go
- mesh/v1alpha1/config.proto
- mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
fix a smart quote so the resulting doc will pass lint.
> manual cherrypick of #3359

- networking/v1alpha3/virtual_service.pb.go
- networking/v1alpha3/virtual_service.pb.html
- networking/v1alpha3/virtual_service.proto
We [excluded](https://github.com/istio/istio/pull/52111) 503 from retries. But did not update the docs
> fix virtual service retry docs

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
Manual cherry-pick of #3455
Closes https://github.com/istio/api/issues/3457
> [release-1.24] Remove non-zero requirement on connectionPool.tcp.IdleTimeout (#3455)

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/destination_rule.pb.go
- networking/v1alpha3/destination_rule.proto
Manual cherry-pick of https://github.com/istio/api/pull/3455
Closes https://github.com/istio/api/issues/3456
> [release-1.23] Remove non-zero requirement on connectionPool.tcp.IdleTimeout (#3455)

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
xref: https://github.com/istio/istio/issues/52082
> add annotation for statsCompression

- annotation/annotations.gen.go
- annotation/annotations.pb.html
- annotation/annotations.yaml
Per discussion in Slack: https://istio.slack.com/archives/C50V5EATT/p1753200025888989
Unhiding `ambient.istio.io/bypass-inbound-capture` to make it more visible.
> unhide ambient.istio.io/bypass-inbound-capture annotation

- kubernetes/customresourcedefinitions.gen.yaml
- networking/v1alpha3/gateway.pb.go
- networking/v1alpha3/gateway.pb.html
- networking/v1alpha3/gateway.proto
- releasenotes/notes/3544.yaml
Docs for PR https://github.com/istio/istio/pull/56549
Related usage docs PR https://github.com/istio/istio.io/pull/16719
> feat: add tls.caCertCredentialName

- kubernetes/customresourcedefinitions.gen.yaml
- releasenotes/notes/storage-version-security.yaml
- security/v1/authorization_policy_alias.gen.go
- security/v1/peer_authentication_alias.gen.go
- security/v1/request_authentication_alias.gen.go
- security/v1beta1/authorization_policy.pb.go
- security/v1beta1/authorization_policy.proto
- security/v1beta1/peer_authentication.pb.go
- security/v1beta1/peer_authentication.proto
- security/v1beta1/request_authentication.pb.go
- security/v1beta1/request_authentication.proto
Discussion: https://istio.slack.com/archives/C37A4KAAD/p1758190615806769
Related: https://github.com/istio/istio/issues/55302
> Migrate storage version of security APIs to v1
